from __future__ import annotations

from uuid import uuid4

import hashlib
import json
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

from invoice_pdf_service import (
    InvoicePDFError,
    InvoicePDFService,
)
from storage.postgres_compat import (
    PostgresConnection,
    connect_database,
)
from subscription_service import SubscriptionError


BILLING_PERIOD_MONTHS = (
    1,
    2,
    3,
    6,
    12,
)

INVOICE_PREFIX = "SPY"


def now_iso() -> str:
    return (
        datetime.now()
        .astimezone()
        .isoformat(timespec="seconds")
    )


BILLING_SUPPLIER_SETTING_KEY = "billing_supplier"

DEFAULT_BILLING_SUPPLIER = {
    "name": "",
    "registration_number": "",
    "legal_address": "",
    "iban": "",
    "bank_name": "",
    "bic": "",
    "kbe": "",
    "payment_purpose_code": "",
    "vat_enabled": False,
    "vat_rate": 0.0,
    "invoice_due_days": 5,
    "invoice_prefix": "SPY",
    "service_name": (
        "\u0410\u0431\u043e\u043d\u0435\u043d\u0442\u0441\u043a\u0430\u044f "
        "\u043f\u043b\u0430\u0442\u0430 "
        "\u043f\u043e "
        "\u0441\u043e\u043f\u0440\u043e\u0432\u043e\u0436\u0434\u0435\u043d\u0438\u044e "
        "\u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u043d\u043e\u0433\u043e "
        "\u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430"
    ),
    "agreement_basis": "",
    "executor_name": "",
}

BILLING_SUPPLIER_REQUIRED_FIELDS = (
    "name",
    "registration_number",
    "legal_address",
    "iban",
    "bank_name",
    "bic",
)

def _as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value

    if value is None:
        return False

    if isinstance(value, (int, float)):
        return value != 0

    text = str(value).strip().casefold()

    if text in {
        "1",
        "true",
        "yes",
        "on",
    }:
        return True

    if text in {
        "",
        "0",
        "false",
        "no",
        "off",
    }:
        return False

    raise SubscriptionError(
        "???????????? ?????????? ????????."
    )


PAYMENT_PROOF_MAX_BYTES = 10 * 1024 * 1024

PAYMENT_PROOF_MIME_TYPES = {
    ".pdf": "application/pdf",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
}


class BillingService:
    """Invoice and payment-domain operations for subscriptions."""

    def __init__(
        self,
        db_path: Path,
        *,
        document_root: Path | None = None,
        invoice_pdf_service: InvoicePDFService | None = None,
    ) -> None:
        self.db_path = Path(db_path)

        self.document_root = (
            Path(document_root)
            if document_root is not None
            else Path.cwd()
        ).resolve()

        self.invoice_pdf_service = (
            invoice_pdf_service
        )

        self.ensure_invoice_schema()

    def _connect(
        self,
    ) -> sqlite3.Connection:
        conn = connect_database(
            self.db_path,
            timeout=30,
        )
        conn.row_factory = sqlite3.Row
        conn.execute(
            "PRAGMA foreign_keys=ON"
        )
        conn.execute(
            "PRAGMA busy_timeout=30000"
        )
        return conn

    def ensure_invoice_schema(self) -> None:
        conn = self._connect()

        try:
            if isinstance(
                conn,
                PostgresConnection,
            ):
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS billing_sequences(
                           sequence_year INTEGER PRIMARY KEY,
                           last_value BIGINT NOT NULL DEFAULT 0
                       )"""
                )

                conn.execute(
                    """CREATE TABLE IF NOT EXISTS subscription_invoices(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY
                               PRIMARY KEY,
                           tenant_id BIGINT NOT NULL
                               REFERENCES tenants(id)
                               ON DELETE CASCADE,
                           subscription_id BIGINT NOT NULL
                               REFERENCES tenant_subscriptions(id)
                               ON DELETE CASCADE,
                           invoice_number TEXT NOT NULL UNIQUE,
                           status TEXT NOT NULL DEFAULT 'issued',
                           months_count INTEGER NOT NULL,
                           unit_price DOUBLE PRECISION
                               NOT NULL DEFAULT 0,
                           subtotal_amount DOUBLE PRECISION
                               NOT NULL DEFAULT 0,
                           vat_rate DOUBLE PRECISION
                               NOT NULL DEFAULT 0,
                           vat_amount DOUBLE PRECISION
                               NOT NULL DEFAULT 0,
                           total_amount DOUBLE PRECISION
                               NOT NULL DEFAULT 0,
                           currency TEXT NOT NULL DEFAULT 'KZT',
                           seller_snapshot_json TEXT
                               NOT NULL DEFAULT '{}',
                           buyer_snapshot_json TEXT
                               NOT NULL DEFAULT '{}',
                           line_items_json TEXT
                               NOT NULL DEFAULT '[]',
                           issued_at TEXT NOT NULL,
                           due_at TEXT,
                           pdf_path TEXT NOT NULL DEFAULT '',
                           pdf_sha256 TEXT NOT NULL DEFAULT '',
                           created_by BIGINT
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           cancelled_by BIGINT
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           cancelled_at TEXT,
                           cancel_reason TEXT NOT NULL DEFAULT '',
                           created_at TEXT NOT NULL,
                           updated_at TEXT NOT NULL
                       )"""
                )
            else:
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS billing_sequences(
                           sequence_year INTEGER PRIMARY KEY,
                           last_value INTEGER NOT NULL DEFAULT 0
                       )"""
                )

                conn.execute(
                    """CREATE TABLE IF NOT EXISTS subscription_invoices(
                           id INTEGER PRIMARY KEY AUTOINCREMENT,
                           tenant_id INTEGER NOT NULL,
                           subscription_id INTEGER NOT NULL,
                           invoice_number TEXT NOT NULL UNIQUE,
                           status TEXT NOT NULL DEFAULT 'issued',
                           months_count INTEGER NOT NULL,
                           unit_price REAL NOT NULL DEFAULT 0,
                           subtotal_amount REAL NOT NULL DEFAULT 0,
                           vat_rate REAL NOT NULL DEFAULT 0,
                           vat_amount REAL NOT NULL DEFAULT 0,
                           total_amount REAL NOT NULL DEFAULT 0,
                           currency TEXT NOT NULL DEFAULT 'KZT',
                           seller_snapshot_json TEXT
                               NOT NULL DEFAULT '{}',
                           buyer_snapshot_json TEXT
                               NOT NULL DEFAULT '{}',
                           line_items_json TEXT
                               NOT NULL DEFAULT '[]',
                           issued_at TEXT NOT NULL,
                           due_at TEXT,
                           pdf_path TEXT NOT NULL DEFAULT '',
                           pdf_sha256 TEXT NOT NULL DEFAULT '',
                           created_by INTEGER,
                           cancelled_by INTEGER,
                           cancelled_at TEXT,
                           cancel_reason TEXT NOT NULL DEFAULT '',
                           created_at TEXT NOT NULL,
                           updated_at TEXT NOT NULL,
                           FOREIGN KEY(tenant_id)
                               REFERENCES tenants(id)
                               ON DELETE CASCADE,
                           FOREIGN KEY(subscription_id)
                               REFERENCES tenant_subscriptions(id)
                               ON DELETE CASCADE,
                           FOREIGN KEY(created_by)
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           FOREIGN KEY(cancelled_by)
                               REFERENCES app_users(id)
                               ON DELETE SET NULL
                       )"""
                )

            if isinstance(
                conn,
                PostgresConnection,
            ):
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS
                       subscription_payment_proofs(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY
                               PRIMARY KEY,
                           tenant_id BIGINT NOT NULL
                               REFERENCES tenants(id)
                               ON DELETE CASCADE,
                           subscription_id BIGINT NOT NULL
                               REFERENCES tenant_subscriptions(id)
                               ON DELETE CASCADE,
                           invoice_id BIGINT NOT NULL
                               REFERENCES subscription_invoices(id)
                               ON DELETE CASCADE,
                           status TEXT NOT NULL
                               DEFAULT 'under_review',
                           original_filename TEXT NOT NULL
                               DEFAULT '',
                           stored_path TEXT NOT NULL UNIQUE,
                           mime_type TEXT NOT NULL
                               DEFAULT '',
                           file_size BIGINT NOT NULL
                               DEFAULT 0,
                           sha256 TEXT NOT NULL
                               DEFAULT '',
                           uploaded_by BIGINT
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           uploaded_at TEXT NOT NULL,
                           reviewed_by BIGINT
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           reviewed_at TEXT,
                           review_note TEXT NOT NULL
                               DEFAULT '',
                           created_at TEXT NOT NULL,
                           updated_at TEXT NOT NULL
                       )"""
                )
            else:
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS
                       subscription_payment_proofs(
                           id INTEGER PRIMARY KEY AUTOINCREMENT,
                           tenant_id INTEGER NOT NULL,
                           subscription_id INTEGER NOT NULL,
                           invoice_id INTEGER NOT NULL,
                           status TEXT NOT NULL
                               DEFAULT 'under_review',
                           original_filename TEXT NOT NULL
                               DEFAULT '',
                           stored_path TEXT NOT NULL UNIQUE,
                           mime_type TEXT NOT NULL
                               DEFAULT '',
                           file_size INTEGER NOT NULL
                               DEFAULT 0,
                           sha256 TEXT NOT NULL
                               DEFAULT '',
                           uploaded_by INTEGER,
                           uploaded_at TEXT NOT NULL,
                           reviewed_by INTEGER,
                           reviewed_at TEXT,
                           review_note TEXT NOT NULL
                               DEFAULT '',
                           created_at TEXT NOT NULL,
                           updated_at TEXT NOT NULL,
                           FOREIGN KEY(tenant_id)
                               REFERENCES tenants(id)
                               ON DELETE CASCADE,
                           FOREIGN KEY(subscription_id)
                               REFERENCES tenant_subscriptions(id)
                               ON DELETE CASCADE,
                           FOREIGN KEY(invoice_id)
                               REFERENCES subscription_invoices(id)
                               ON DELETE CASCADE,
                           FOREIGN KEY(uploaded_by)
                               REFERENCES app_users(id)
                               ON DELETE SET NULL,
                           FOREIGN KEY(reviewed_by)
                               REFERENCES app_users(id)
                               ON DELETE SET NULL
                       )"""
                )

            conn.execute(
                """CREATE INDEX IF NOT EXISTS
                   idx_subscription_payment_proofs_invoice
                   ON subscription_payment_proofs(
                       invoice_id,uploaded_at DESC
                   )"""
            )

            conn.execute(
                """CREATE INDEX IF NOT EXISTS
                   idx_subscription_payment_proofs_tenant
                   ON subscription_payment_proofs(
                       tenant_id,status,uploaded_at DESC
                   )"""
            )

            conn.execute(
                """CREATE UNIQUE INDEX IF NOT EXISTS
                   idx_subscription_payment_proofs_review_open
                   ON subscription_payment_proofs(invoice_id)
                   WHERE status='under_review'"""
            )

            conn.execute(
                """CREATE INDEX IF NOT EXISTS
                   idx_subscription_invoices_tenant
                   ON subscription_invoices(
                       tenant_id,status,issued_at DESC
                   )"""
            )

            conn.execute(
                """CREATE INDEX IF NOT EXISTS
                   idx_subscription_invoices_subscription
                   ON subscription_invoices(
                       subscription_id,issued_at DESC
                   )"""
            )

            conn.execute(
                """CREATE UNIQUE INDEX IF NOT EXISTS
                   idx_subscription_invoices_open
                   ON subscription_invoices(subscription_id)
                   WHERE status<>'cancelled'"""
            )

            conn.commit()

        finally:
            conn.close()

    @staticmethod
    def _supplier_status(
        value: dict[str, Any],
    ) -> dict[str, Any]:
        missing = [
            field
            for field
            in BILLING_SUPPLIER_REQUIRED_FIELDS
            if not str(
                value.get(field)
                or ""
            ).strip()
        ]

        result = dict(value)

        result["is_complete"] = (
            not missing
        )

        result["missing_fields"] = (
            missing
        )

        return result

    def supplier_settings(
        self,
    ) -> dict[str, Any]:
        value = dict(
            DEFAULT_BILLING_SUPPLIER
        )

        conn = self._connect()

        try:
            row = conn.execute(
                """SELECT value_json
                   FROM platform_settings
                   WHERE setting_key=?""",
                (
                    BILLING_SUPPLIER_SETTING_KEY,
                ),
            ).fetchone()
        finally:
            conn.close()

        if row:
            try:
                stored = json.loads(
                    str(
                        row["value_json"]
                        or "{}"
                    )
                )
            except json.JSONDecodeError:
                stored = {}

            if isinstance(
                stored,
                dict,
            ):
                for key in (
                    DEFAULT_BILLING_SUPPLIER
                ):
                    if key in stored:
                        value[key] = (
                            stored[key]
                        )

        try:
            value[
                "invoice_due_days"
            ] = int(
                value.get(
                    "invoice_due_days",
                    5,
                )
                or 5
            )
        except (
            TypeError,
            ValueError,
        ):
            value[
                "invoice_due_days"
            ] = 5

        try:
            value[
                "vat_rate"
            ] = float(
                value.get(
                    "vat_rate",
                    0,
                )
                or 0
            )
        except (
            TypeError,
            ValueError,
        ):
            value[
                "vat_rate"
            ] = 0.0

        try:
            value[
                "vat_enabled"
            ] = _as_bool(
                value.get(
                    "vat_enabled",
                    False,
                )
            )
        except SubscriptionError:
            value[
                "vat_enabled"
            ] = False

        return self._supplier_status(
            value
        )

    def update_supplier_settings(
        self,
        payload: dict[str, Any],
        actor_user_id: int,
    ) -> dict[str, Any]:
        if not isinstance(
            payload,
            dict,
        ):
            raise SubscriptionError(
                "\u041d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0435 "
                "\u0440\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b "
                "\u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430."
            )

        current = (
            self.supplier_settings()
        )

        # Derived fields are never persisted.
        current.pop(
            "is_complete",
            None,
        )
        current.pop(
            "missing_fields",
            None,
        )

        text_fields = {
            "name",
            "registration_number",
            "legal_address",
            "iban",
            "bank_name",
            "bic",
            "kbe",
            "payment_purpose_code",
            "invoice_prefix",
            "service_name",
            "agreement_basis",
            "executor_name",
        }

        for key in text_fields:
            if key not in payload:
                continue

            current[key] = str(
                payload.get(key)
                or ""
            ).strip()

        if "vat_enabled" in payload:
            current[
                "vat_enabled"
            ] = _as_bool(
                payload.get(
                    "vat_enabled"
                )
            )

        if "vat_rate" in payload:
            try:
                vat_rate = float(
                    payload.get(
                        "vat_rate"
                    )
                    or 0
                )
            except (
                TypeError,
                ValueError,
            ):
                raise SubscriptionError(
                    "\u0421\u0442\u0430\u0432\u043a\u0430 "
                    "\u041d\u0414\u0421 "
                    "\u0434\u043e\u043b\u0436\u043d\u0430 "
                    "\u0431\u044b\u0442\u044c "
                    "\u0447\u0438\u0441\u043b\u043e\u043c."
                )

            if not 0 <= vat_rate <= 100:
                raise SubscriptionError(
                    "\u0421\u0442\u0430\u0432\u043a\u0430 "
                    "\u041d\u0414\u0421 "
                    "\u0434\u043e\u043b\u0436\u043d\u0430 "
                    "\u0431\u044b\u0442\u044c "
                    "\u043e\u0442 0 "
                    "\u0434\u043e 100."
                )

            current[
                "vat_rate"
            ] = vat_rate

        if "invoice_due_days" in payload:
            raw_due_days = payload.get(
                "invoice_due_days"
            )

            if raw_due_days in (
                None,
                "",
            ):
                raw_due_days = 5

            try:
                due_days = int(
                    raw_due_days
                )
            except (
                TypeError,
                ValueError,
            ):
                raise SubscriptionError(
                    "\u0421\u0440\u043e\u043a "
                    "\u043e\u043f\u043b\u0430\u0442\u044b "
                    "\u0441\u0447\u0451\u0442\u0430 "
                    "\u0434\u043e\u043b\u0436\u0435\u043d "
                    "\u0431\u044b\u0442\u044c "
                    "\u0447\u0438\u0441\u043b\u043e\u043c."
                )

            if not 1 <= due_days <= 90:
                raise SubscriptionError(
                    "\u0421\u0440\u043e\u043a "
                    "\u043e\u043f\u043b\u0430\u0442\u044b "
                    "\u0441\u0447\u0451\u0442\u0430 "
                    "\u0434\u043e\u043b\u0436\u0435\u043d "
                    "\u0431\u044b\u0442\u044c "
                    "\u043e\u0442 1 "
                    "\u0434\u043e 90 "
                    "\u0434\u043d\u0435\u0439."
                )

            current[
                "invoice_due_days"
            ] = due_days

        prefix = str(
            current.get(
                "invoice_prefix"
            )
            or "SPY"
        ).strip().upper()

        prefix = "".join(
            char
            for char in prefix
            if (
                char.isascii()
                and (
                    char.isalnum()
                    or char in {"-", "_"}
                )
            )
        )

        if not 2 <= len(prefix) <= 12:
            raise SubscriptionError(
                "\u041f\u0440\u0435\u0444\u0438\u043a\u0441 "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u0434\u043e\u043b\u0436\u0435\u043d "
                "\u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0442\u044c "
                "\u043e\u0442 2 "
                "\u0434\u043e 12 "
                "\u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432."
            )

        current[
            "invoice_prefix"
        ] = prefix

        if not current.get(
            "vat_enabled"
        ):
            current[
                "vat_rate"
            ] = 0.0

        stamp = now_iso()

        conn = self._connect()

        try:
            conn.execute(
                """INSERT INTO platform_settings(
                       setting_key,
                       value_json,
                       updated_by,
                       updated_at
                   )
                   VALUES(?,?,?,?)
                   ON CONFLICT(setting_key)
                   DO UPDATE SET
                       value_json=excluded.value_json,
                       updated_by=excluded.updated_by,
                       updated_at=excluded.updated_at""",
                (
                    BILLING_SUPPLIER_SETTING_KEY,
                    json.dumps(
                        current,
                        ensure_ascii=False,
                        separators=(",", ":"),
                    ),
                    int(actor_user_id),
                    stamp,
                ),
            )

            conn.execute(
                """INSERT INTO platform_audit_log(
                       actor_user_id,
                       action,
                       tenant_id,
                       entity_type,
                       entity_id,
                       details_json,
                       created_at
                   )
                   VALUES(
                       ?,?,
                       NULL,
                       ?,?,?,?
                   )""",
                (
                    int(actor_user_id),
                    "billing_supplier_settings_updated",
                    "platform_settings",
                    BILLING_SUPPLIER_SETTING_KEY,
                    json.dumps(
                        {
                            "updated_fields":
                                sorted(
                                    key
                                    for key
                                    in payload
                                    if key
                                    in DEFAULT_BILLING_SUPPLIER
                                ),
                            "is_complete":
                                self._supplier_status(
                                    current
                                )[
                                    "is_complete"
                                ],
                        },
                        ensure_ascii=False,
                        separators=(",", ":"),
                    ),
                    stamp,
                ),
            )

            conn.commit()

        except Exception:
            conn.rollback()
            raise

        finally:
            conn.close()

        return self._supplier_status(
            current
        )

    @staticmethod
    def allowed_billing_periods() -> list[int]:
        return list(
            BILLING_PERIOD_MONTHS
        )

    @staticmethod
    def _invoice_dict(
        row: Any,
    ) -> dict[str, Any]:
        value = dict(row)

        mappings = (
            (
                "seller_snapshot_json",
                "seller",
                {},
            ),
            (
                "buyer_snapshot_json",
                "buyer",
                {},
            ),
            (
                "line_items_json",
                "line_items",
                [],
            ),
        )

        for source, target, fallback in mappings:
            raw = value.pop(
                source,
                None,
            )

            try:
                value[target] = json.loads(
                    str(raw or "")
                )
            except (
                json.JSONDecodeError,
                TypeError,
            ):
                value[target] = fallback

        return value

    def _next_invoice_number(
        self,
        conn: sqlite3.Connection,
        moment: datetime,
    ) -> str:
        year = int(
            moment.year
        )

        conn.execute(
            """INSERT INTO billing_sequences(
                   sequence_year,last_value
               )
               VALUES(?,0)
               ON CONFLICT(sequence_year)
               DO NOTHING""",
            (year,),
        )

        query = (
            """SELECT last_value
               FROM billing_sequences
               WHERE sequence_year=?"""
        )

        if isinstance(
            conn,
            PostgresConnection,
        ):
            query += " FOR UPDATE"

        row = conn.execute(
            query,
            (year,),
        ).fetchone()

        if not row:
            raise SubscriptionError(
                "\u041d\u0435 "
                "\u0443\u0434\u0430\u043b\u043e\u0441\u044c "
                "\u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u0442\u044c "
                "\u043d\u043e\u043c\u0435\u0440 "
                "\u0441\u0447\u0451\u0442\u0430."
            )

        next_value = int(
            row[0]
        ) + 1

        conn.execute(
            """UPDATE billing_sequences
               SET last_value=?
               WHERE sequence_year=?""",
            (
                next_value,
                year,
            ),
        )

        return (
            f"{INVOICE_PREFIX}-"
            f"{year}-"
            f"{next_value:06d}"
        )

    def invoice_by_id(
        self,
        invoice_id: int,
    ) -> dict[str, Any] | None:
        conn = self._connect()

        try:
            row = conn.execute(
                """SELECT *
                   FROM subscription_invoices
                   WHERE id=?
                   LIMIT 1""",
                (
                    int(invoice_id),
                ),
            ).fetchone()

            return (
                self._invoice_dict(row)
                if row
                else None
            )

        finally:
            conn.close()

    @staticmethod
    def _invoice_pdf_payload(
        invoice: dict[str, Any],
    ) -> dict[str, Any]:
        payload = dict(invoice)

        payload["seller_snapshot"] = dict(
            invoice.get("seller")
            or {}
        )

        payload["buyer_snapshot"] = dict(
            invoice.get("buyer")
            or {}
        )

        payload["line_items"] = list(
            invoice.get("line_items")
            or []
        )

        return payload

    @staticmethod
    def _invoice_year(
        invoice: dict[str, Any],
    ) -> int:
        raw = str(
            invoice.get("issued_at")
            or ""
        ).strip()

        if not raw:
            raise SubscriptionError(
                "\u0423 "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u043d\u0435 "
                "\u0443\u043a\u0430\u0437\u0430\u043d\u0430 "
                "\u0434\u0430\u0442\u0430 "
                "\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f."
            )

        try:
            value = datetime.fromisoformat(
                raw.replace(
                    "Z",
                    "+00:00",
                )
            )
        except ValueError as exc:
            raise SubscriptionError(
                "\u041d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u0430\u044f "
                "\u0434\u0430\u0442\u0430 "
                "\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f "
                "\u0441\u0447\u0451\u0442\u0430."
            ) from exc

        return int(
            value.year
        )

    def _default_invoice_pdf_service(
        self,
        invoice: dict[str, Any],
    ) -> InvoicePDFService:
        year = self._invoice_year(
            invoice
        )

        return InvoicePDFService(
            output_dir=(
                self.document_root
                / "output"
                / "invoices"
                / str(year)
            ),
            logo_path=(
                self.document_root
                / "static"
                / "billing"
                / "itp_mining_logo.png"
            ),
            stamp_path=(
                self.document_root
                / "data"
                / "billing-assets"
                / "itp_mining_stamp.png"
            ),
        )

    def _invoice_storage_root(
        self,
    ) -> Path:
        return (
            self.document_root
            / "output"
            / "invoices"
        ).resolve()

    def _normalize_invoice_file(
        self,
        path_value: str | Path,
    ) -> Path:
        raw = Path(
            path_value
        )

        if raw.is_absolute():
            resolved = raw.resolve()
        else:
            resolved = (
                self.document_root
                / raw
            ).resolve()

        root = (
            self._invoice_storage_root()
        )

        try:
            resolved.relative_to(
                root
            )
        except ValueError as exc:
            raise SubscriptionError(
                "\u041d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0439 "
                "\u043f\u0443\u0442\u044c "
                "\u043a PDF "
                "\u0441\u0447\u0451\u0442\u0430."
            ) from exc

        return resolved

    def _relative_invoice_file(
        self,
        file_path: Path,
    ) -> str:
        resolved = (
            self._normalize_invoice_file(
                file_path
            )
        )

        try:
            relative = resolved.relative_to(
                self.document_root
            )
        except ValueError as exc:
            raise SubscriptionError(
                "\u041d\u0435 "
                "\u0443\u0434\u0430\u043b\u043e\u0441\u044c "
                "\u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c "
                "\u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 "
                "\u043f\u0443\u0442\u044c "
                "\u043a PDF "
                "\u0441\u0447\u0451\u0442\u0430."
            ) from exc

        return relative.as_posix()

    @staticmethod
    def _file_sha256(
        file_path: Path,
    ) -> str:
        digest = hashlib.sha256()

        with file_path.open(
            "rb"
        ) as stream:
            for chunk in iter(
                lambda: stream.read(
                    1024 * 1024
                ),
                b"",
            ):
                digest.update(
                    chunk
                )

        return digest.hexdigest()

    def invoice_pdf(
        self,
        invoice_id: int,
    ) -> dict[str, Any]:
        invoice = self.invoice_by_id(
            int(invoice_id)
        )

        if not invoice:
            raise SubscriptionError(
                "\u0421\u0447\u0451\u0442 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        relative_path = str(
            invoice.get("pdf_path")
            or ""
        ).strip()

        expected_sha256 = str(
            invoice.get("pdf_sha256")
            or ""
        ).strip().lower()

        if (
            not relative_path
            and not expected_sha256
        ):
            raise SubscriptionError(
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u0435\u0449\u0451 "
                "\u043d\u0435 "
                "\u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d."
            )

        if (
            not relative_path
            or not expected_sha256
        ):
            raise SubscriptionError(
                "\u041c\u0435\u0442\u0430\u0434\u0430\u043d\u043d\u044b\u0435 "
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u043f\u043e\u0432\u0440\u0435\u0436\u0434\u0435\u043d\u044b."
            )

        file_path = (
            self._normalize_invoice_file(
                relative_path
            )
        )

        if not file_path.is_file():
            raise SubscriptionError(
                "\u0424\u0430\u0439\u043b "
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442."
            )

        actual_sha256 = (
            self._file_sha256(
                file_path
            )
        )

        if (
            actual_sha256
            != expected_sha256
        ):
            raise SubscriptionError(
                "\u041d\u0430\u0440\u0443\u0448\u0435\u043d\u0430 "
                "\u0446\u0435\u043b\u043e\u0441\u0442\u043d\u043e\u0441\u0442\u044c "
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430."
            )

        return {
            "invoice": invoice,
            "path": file_path,
            "relative_path":
                relative_path,
            "sha256":
                actual_sha256,
            "size":
                int(
                    file_path.stat().st_size
                ),
        }

    def generate_invoice_pdf(
        self,
        invoice_id: int,
    ) -> dict[str, Any]:
        invoice = self.invoice_by_id(
            int(invoice_id)
        )

        if not invoice:
            raise SubscriptionError(
                "\u0421\u0447\u0451\u0442 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        if str(
            invoice.get("status")
            or ""
        ) == "cancelled":
            raise SubscriptionError(
                "\u0414\u043b\u044f "
                "\u043e\u0442\u043c\u0435\u043d\u0451\u043d\u043d\u043e\u0433\u043e "
                "\u0441\u0447\u0451\u0442\u0430 "
                "PDF "
                "\u043d\u0435 "
                "\u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f."
            )

        current_path = str(
            invoice.get("pdf_path")
            or ""
        ).strip()

        current_sha = str(
            invoice.get("pdf_sha256")
            or ""
        ).strip()

        if (
            current_path
            or current_sha
        ):
            return self.invoice_pdf(
                int(invoice_id)
            )

        service = (
            self.invoice_pdf_service
            or self._default_invoice_pdf_service(
                invoice
            )
        )

        payload = (
            self._invoice_pdf_payload(
                invoice
            )
        )

        try:
            generated = service.generate(
                payload
            )
        except InvoicePDFError as exc:
            raise SubscriptionError(
                "\u041d\u0435 "
                "\u0443\u0434\u0430\u043b\u043e\u0441\u044c "
                "\u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u0442\u044c "
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430."
            ) from exc

        generated_path_raw = str(
            generated.get("path")
            or ""
        ).strip()

        generated_sha = str(
            generated.get("sha256")
            or ""
        ).strip().lower()

        if not generated_path_raw:
            raise SubscriptionError(
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u043d\u0435 "
                "\u0431\u044b\u043b "
                "\u0441\u043e\u0445\u0440\u0430\u043d\u0451\u043d."
            )

        generated_path = (
            self._normalize_invoice_file(
                generated_path_raw
            )
        )

        if not generated_path.is_file():
            raise SubscriptionError(
                "\u0421\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 "
                "PDF "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        actual_sha = (
            self._file_sha256(
                generated_path
            )
        )

        if (
            generated_sha
            and generated_sha
            != actual_sha
        ):
            raise SubscriptionError(
                "\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u0430\u044f "
                "\u0441\u0443\u043c\u043c\u0430 "
                "\u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u043e\u0433\u043e "
                "PDF "
                "\u043d\u0435 "
                "\u0441\u043e\u0432\u043f\u0430\u0434\u0430\u0435\u0442."
            )

        relative_path = (
            self._relative_invoice_file(
                generated_path
            )
        )

        conn = self._connect()

        try:
            conn.execute(
                """UPDATE subscription_invoices
                   SET pdf_path=?,
                       pdf_sha256=?,
                       updated_at=?
                   WHERE id=?
                     AND COALESCE(pdf_path, '')=''
                     AND COALESCE(pdf_sha256, '')=''""",
                (
                    relative_path,
                    actual_sha,
                    now_iso(),
                    int(invoice_id),
                ),
            )

            stored = conn.execute(
                """SELECT pdf_path,
                          pdf_sha256
                   FROM subscription_invoices
                   WHERE id=?""",
                (
                    int(invoice_id),
                ),
            ).fetchone()

            if not stored:
                raise SubscriptionError(
                    "\u0421\u0447\u0451\u0442 "
                    "\u043d\u0435 "
                    "\u043d\u0430\u0439\u0434\u0435\u043d."
                )

            stored_path = str(
                stored["pdf_path"]
                or ""
            )

            stored_sha = str(
                stored["pdf_sha256"]
                or ""
            ).lower()

            if (
                stored_path
                != relative_path
                or stored_sha
                != actual_sha
            ):
                raise SubscriptionError(
                    "\u041a\u043e\u043d\u0444\u043b\u0438\u043a\u0442 "
                    "\u043f\u0440\u0438 "
                    "\u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u0438 "
                    "PDF "
                    "\u0441\u0447\u0451\u0442\u0430."
                )

            conn.commit()

        except Exception:
            conn.rollback()
            raise

        finally:
            conn.close()

        return self.invoice_pdf(
            int(invoice_id)
        )

    @staticmethod
    def _payment_proof_dict(
        row: Any,
    ) -> dict[str, Any]:
        return dict(row)

    def _payment_proof_storage_root(
        self,
    ) -> Path:
        return (
            self.document_root
            / "data"
            / "billing"
            / "payment-proofs"
        ).resolve()

    def _normalize_payment_proof_file(
        self,
        path: Path,
    ) -> Path:
        value = Path(path)

        if not value.is_absolute():
            value = (
                self.document_root
                / value
            )

        value = value.resolve()
        root = (
            self
            ._payment_proof_storage_root()
        )

        if root not in value.parents:
            raise SubscriptionError(
                "\u041d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0439 "
                "\u043f\u0443\u0442\u044c "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430."
            )

        return value

    def _relative_payment_proof_file(
        self,
        path: Path,
    ) -> str:
        value = (
            self
            ._normalize_payment_proof_file(
                path
            )
        )

        try:
            relative = value.relative_to(
                self.document_root
            )
        except ValueError:
            raise SubscriptionError(
                "\u041d\u0435\u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u043e\u0435 "
                "\u0440\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430."
            )

        return relative.as_posix()

    @staticmethod
    def _validate_payment_proof_content(
        original_filename: str,
        mime_type: str,
        content: bytes,
    ) -> tuple[str, str]:
        filename = str(
            original_filename
            or ""
        ).strip()

        if not filename:
            raise SubscriptionError(
                "\u0418\u043c\u044f "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 "
                "\u043d\u0435 "
                "\u0443\u043a\u0430\u0437\u0430\u043d\u043e."
            )

        extension = (
            Path(filename)
            .suffix
            .lower()
        )

        expected_mime = (
            PAYMENT_PROOF_MIME_TYPES
            .get(extension)
        )

        if not expected_mime:
            raise SubscriptionError(
                "\u0420\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u044b "
                "\u0442\u043e\u043b\u044c\u043a\u043e "
                "PDF, JPG, JPEG "
                "\u0438 PNG."
            )

        actual_mime = str(
            mime_type
            or ""
        ).strip().lower()

        if actual_mime != expected_mime:
            raise SubscriptionError(
                "\u0422\u0438\u043f "
                "\u0444\u0430\u0439\u043b\u0430 "
                "\u043d\u0435 "
                "\u0441\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 "
                "\u0435\u0433\u043e "
                "\u0440\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u0438\u044e."
            )

        if not content:
            raise SubscriptionError(
                "\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u044b\u0439 "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442 "
                "\u043f\u0443\u0441\u0442."
            )

        if len(content) > PAYMENT_PROOF_MAX_BYTES:
            raise SubscriptionError(
                "\u0420\u0430\u0437\u043c\u0435\u0440 "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 "
                "\u043d\u0435 "
                "\u0434\u043e\u043b\u0436\u0435\u043d "
                "\u043f\u0440\u0435\u0432\u044b\u0448\u0430\u0442\u044c "
                "10 MB."
            )

        valid_signature = False

        if extension == ".pdf":
            valid_signature = (
                content.startswith(
                    b"%PDF-"
                )
            )

        elif extension in {
            ".jpg",
            ".jpeg",
        }:
            valid_signature = (
                len(content) >= 3
                and content[:3]
                == b"\xff\xd8\xff"
            )

        elif extension == ".png":
            valid_signature = (
                content.startswith(
                    b"\x89PNG\r\n\x1a\n"
                )
            )

        if not valid_signature:
            raise SubscriptionError(
                "\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 "
                "\u0444\u0430\u0439\u043b\u0430 "
                "\u043d\u0435 "
                "\u0441\u043e\u043e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0443\u0435\u0442 "
                "\u0435\u0433\u043e "
                "\u0442\u0438\u043f\u0443."
            )

        canonical_extension = (
            ".jpg"
            if extension == ".jpeg"
            else extension
        )

        return (
            canonical_extension,
            expected_mime,
        )

    def payment_proof_for_invoice(
        self,
        invoice_id: int,
        *,
        tenant_id: int | None = None,
    ) -> dict[str, Any] | None:
        conn = self._connect()

        try:
            query = """SELECT *
                       FROM subscription_payment_proofs
                       WHERE invoice_id=?"""

            params: list[Any] = [
                int(invoice_id),
            ]

            if tenant_id is not None:
                query += " AND tenant_id=?"
                params.append(
                    int(tenant_id)
                )

            query += """
                       ORDER BY
                           CASE status
                               WHEN 'under_review' THEN 0
                               WHEN 'rejected' THEN 1
                               WHEN 'confirmed' THEN 2
                               ELSE 3
                           END,
                           id DESC
                       LIMIT 1"""

            row = conn.execute(
                query,
                tuple(params),
            ).fetchone()

            return (
                self._payment_proof_dict(
                    row
                )
                if row
                else None
            )

        finally:
            conn.close()

    def payment_proof_file(
        self,
        proof_id: int,
        tenant_id: int,
    ) -> dict[str, Any]:
        conn = self._connect()

        try:
            row = conn.execute(
                """SELECT *
                   FROM subscription_payment_proofs
                   WHERE id=?
                     AND tenant_id=?""",
                (
                    int(proof_id),
                    int(tenant_id),
                ),
            ).fetchone()

        finally:
            conn.close()

        if not row:
            raise SubscriptionError(
                "\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u044b\u0439 "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        proof = (
            self
            ._payment_proof_dict(
                row
            )
        )

        path = (
            self
            ._normalize_payment_proof_file(
                Path(
                    str(
                        proof.get(
                            "stored_path"
                        )
                        or ""
                    )
                )
            )
        )

        if not path.is_file():
            raise SubscriptionError(
                "\u0424\u0430\u0439\u043b "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        actual_sha256 = (
            hashlib.sha256(
                path.read_bytes()
            ).hexdigest()
        )

        stored_sha256 = str(
            proof.get(
                "sha256"
            )
            or ""
        )

        if (
            not stored_sha256
            or actual_sha256
            != stored_sha256
        ):
            raise SubscriptionError(
                "\u041a\u043e\u043d\u0442\u0440\u043e\u043b\u044c\u043d\u0430\u044f "
                "\u0441\u0443\u043c\u043c\u0430 "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u043e\u0433\u043e "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 "
                "\u043d\u0435 "
                "\u0441\u043e\u0432\u043f\u0430\u0434\u0430\u0435\u0442."
            )

        return {
            "proof": proof,
            "path": path,
            "sha256": actual_sha256,
            "size": path.stat().st_size,
        }

    def save_payment_proof(
        self,
        invoice_id: int,
        tenant_id: int,
        actor_user_id: int,
        *,
        original_filename: str,
        mime_type: str,
        content: bytes,
    ) -> dict[str, Any]:
        if not isinstance(
            content,
            bytes,
        ):
            content = bytes(
                content
            )

        extension, canonical_mime = (
            self
            ._validate_payment_proof_content(
                original_filename,
                mime_type,
                content,
            )
        )

        conn = self._connect()

        try:
            invoice = conn.execute(
                """SELECT
                       i.id,
                       i.tenant_id,
                       i.subscription_id,
                       i.invoice_number,
                       i.status AS invoice_status,
                       s.status AS subscription_status
                   FROM subscription_invoices i
                   JOIN tenant_subscriptions s
                     ON s.id=i.subscription_id
                   WHERE i.id=?
                     AND i.tenant_id=?""",
                (
                    int(invoice_id),
                    int(tenant_id),
                ),
            ).fetchone()

        finally:
            conn.close()

        if not invoice:
            raise SubscriptionError(
                "\u0421\u0447\u0451\u0442 "
                "\u043d\u0435 "
                "\u043d\u0430\u0439\u0434\u0435\u043d."
            )

        if str(
            invoice[
                "invoice_status"
            ]
            or ""
        ) == "cancelled":
            raise SubscriptionError(
                "\u041d\u0435\u043b\u044c\u0437\u044f "
                "\u043f\u0440\u0438\u043a\u0440\u0435\u043f\u0438\u0442\u044c "
                "\u043e\u043f\u043b\u0430\u0442\u0443 "
                "\u043a "
                "\u043e\u0442\u043c\u0435\u043d\u0451\u043d\u043d\u043e\u043c\u0443 "
                "\u0441\u0447\u0451\u0442\u0443."
            )

        subscription_status = str(
            invoice[
                "subscription_status"
            ]
            or ""
        )

        if subscription_status not in {
            "awaiting_payment",
            "payment_rejected",
        }:
            raise SubscriptionError(
                "\u041f\u043b\u0430\u0442\u0451\u0436\u043d\u044b\u0439 "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442 "
                "\u043c\u043e\u0436\u043d\u043e "
                "\u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c "
                "\u0442\u043e\u043b\u044c\u043a\u043e "
                "\u0434\u043b\u044f "
                "\u0441\u0447\u0451\u0442\u0430, "
                "\u043e\u0436\u0438\u0434\u0430\u044e\u0449\u0435\u0433\u043e "
                "\u043e\u043f\u043b\u0430\u0442\u044b."
            )

        stamp = now_iso()

        year = (
            stamp[:4]
            if len(stamp) >= 4
            else "unknown"
        )

        folder = (
            self
            ._payment_proof_storage_root()
            / year
            / (
                "tenant-"
                + str(
                    int(tenant_id)
                )
            )
            / (
                "invoice-"
                + str(
                    int(invoice_id)
                )
            )
        )

        folder.mkdir(
            parents=True,
            exist_ok=True,
        )

        path = (
            folder
            / (
                uuid4().hex
                + extension
            )
        )

        path = (
            self
            ._normalize_payment_proof_file(
                path
            )
        )

        path.write_bytes(
            content
        )

        sha256 = hashlib.sha256(
            content
        ).hexdigest()

        relative_path = (
            self
            ._relative_payment_proof_file(
                path
            )
        )

        conn = self._connect()

        try:
            conn.execute(
                """UPDATE subscription_payment_proofs
                   SET
                       status='superseded',
                       updated_at=?
                   WHERE invoice_id=?
                     AND status='under_review'""",
                (
                    stamp,
                    int(invoice_id),
                ),
            )

            cursor = conn.execute(
                """UPDATE tenant_subscriptions
                   SET
                       status='payment_review',
                       updated_at=?
                   WHERE id=?
                     AND tenant_id=?
                     AND status IN(
                         'awaiting_payment',
                         'payment_rejected'
                     )""",
                (
                    stamp,
                    int(
                        invoice[
                            "subscription_id"
                        ]
                    ),
                    int(tenant_id),
                ),
            )

            if cursor.rowcount != 1:
                raise SubscriptionError(
                    "\u0421\u0442\u0430\u0442\u0443\u0441 "
                    "\u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0438 "
                    "\u0438\u0437\u043c\u0435\u043d\u0438\u043b\u0441\u044f. "
                    "\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u0435 "
                    "\u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443."
                )

            conn.execute(
                """INSERT INTO subscription_payment_proofs(
                       tenant_id,
                       subscription_id,
                       invoice_id,
                       status,
                       original_filename,
                       stored_path,
                       mime_type,
                       file_size,
                       sha256,
                       uploaded_by,
                       uploaded_at,
                       reviewed_by,
                       reviewed_at,
                       review_note,
                       created_at,
                       updated_at
                   )
                   VALUES(
                       ?,?,?,
                       'under_review',
                       ?,?,?,?,?,
                       ?,?,
                       NULL,NULL,'',
                       ?,?
                   )""",
                (
                    int(tenant_id),
                    int(
                        invoice[
                            "subscription_id"
                        ]
                    ),
                    int(invoice_id),
                    str(
                        original_filename
                        or ""
                    ).strip(),
                    relative_path,
                    canonical_mime,
                    len(content),
                    sha256,
                    int(actor_user_id),
                    stamp,
                    stamp,
                    stamp,
                ),
            )

            row = conn.execute(
                """SELECT *
                   FROM subscription_payment_proofs
                   WHERE stored_path=?""",
                (
                    relative_path,
                ),
            ).fetchone()

            conn.commit()

        except Exception:
            conn.rollback()

            try:
                path.unlink(
                    missing_ok=True
                )
            except OSError:
                pass

            raise

        finally:
            conn.close()

        if not row:
            raise SubscriptionError(
                "\u041d\u0435 "
                "\u0443\u0434\u0430\u043b\u043e\u0441\u044c "
                "\u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c "
                "\u043f\u043b\u0430\u0442\u0451\u0436\u043d\u044b\u0439 "
                "\u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442."
            )

        return (
            self
            ._payment_proof_dict(
                row
            )
        )

    def tenant_billing_snapshot(
        self,
        tenant_id: int,
    ) -> dict[str, Any]:
        conn = self._connect()

        try:
            subscription = conn.execute(
                """SELECT
                       s.id,
                       s.tenant_id,
                       s.status,
                       s.price_amount,
                       s.currency,
                       s.created_at,
                       s.updated_at,
                       p.code AS plan_code,
                       p.name AS plan_name
                   FROM tenant_subscriptions s
                   JOIN subscription_plans p
                     ON p.id=s.plan_id
                   WHERE s.tenant_id=?
                     AND s.status IN(
                         'awaiting_invoice',
                         'awaiting_payment',
                         'payment_review',
                         'payment_rejected'
                     )
                   ORDER BY s.id DESC
                   LIMIT 1""",
                (
                    int(tenant_id),
                ),
            ).fetchone()

            subscription_value = (
                dict(subscription)
                if subscription
                else None
            )

            invoice_value = None

            if subscription:
                invoice = conn.execute(
                    """SELECT *
                       FROM subscription_invoices
                       WHERE subscription_id=?
                         AND status<>'cancelled'
                       ORDER BY id DESC
                       LIMIT 1""",
                    (
                        int(
                            subscription["id"]
                        ),
                    ),
                ).fetchone()

                if invoice:
                    value = self._invoice_dict(
                        invoice
                    )

                    invoice_value = {
                        "id":
                            int(value["id"]),
                        "subscription_id":
                            int(
                                value[
                                    "subscription_id"
                                ]
                            ),
                        "invoice_number":
                            str(
                                value[
                                    "invoice_number"
                                ]
                            ),
                        "status":
                            str(
                                value["status"]
                            ),
                        "months_count":
                            int(
                                value[
                                    "months_count"
                                ]
                            ),
                        "unit_price":
                            float(
                                value[
                                    "unit_price"
                                ]
                            ),
                        "subtotal_amount":
                            float(
                                value[
                                    "subtotal_amount"
                                ]
                            ),
                        "vat_rate":
                            float(
                                value[
                                    "vat_rate"
                                ]
                            ),
                        "vat_amount":
                            float(
                                value[
                                    "vat_amount"
                                ]
                            ),
                        "total_amount":
                            float(
                                value[
                                    "total_amount"
                                ]
                            ),
                        "currency":
                            str(
                                value[
                                    "currency"
                                ]
                            ),
                        "issued_at":
                            str(
                                value[
                                    "issued_at"
                                ]
                            ),
                        "due_at":
                            str(
                                value.get(
                                    "due_at"
                                )
                                or ""
                            ),
                        "pdf_ready":
                            bool(
                                str(
                                    value.get(
                                        "pdf_path"
                                    )
                                    or ""
                                ).strip()
                                and str(
                                    value.get(
                                        "pdf_sha256"
                                    )
                                    or ""
                                ).strip()
                            ),
                    }

        finally:
            conn.close()

        proof_value = None

        if invoice_value:
            proof = (
                self.payment_proof_for_invoice(
                    int(invoice_value["id"]),
                    tenant_id=int(tenant_id),
                )
            )

            if proof:
                proof_value = {
                    "id":
                        int(proof["id"]),
                    "invoice_id":
                        int(proof["invoice_id"]),
                    "status":
                        str(
                            proof.get("status")
                            or ""
                        ),
                    "original_filename":
                        str(
                            proof.get(
                                "original_filename"
                            )
                            or ""
                        ),
                    "mime_type":
                        str(
                            proof.get(
                                "mime_type"
                            )
                            or ""
                        ),
                    "file_size":
                        int(
                            proof.get(
                                "file_size"
                            )
                            or 0
                        ),
                    "uploaded_at":
                        str(
                            proof.get(
                                "uploaded_at"
                            )
                            or ""
                        ),
                    "reviewed_at":
                        str(
                            proof.get(
                                "reviewed_at"
                            )
                            or ""
                        ),
                    "review_note":
                        str(
                            proof.get(
                                "review_note"
                            )
                            or ""
                        ),
                    "download_ready": True,
                }

        supplier = (
            self.supplier_settings()
        )

        ready = bool(
            supplier.get(
                "is_complete"
            )
        )

        can_issue = bool(
            subscription_value
            and str(
                subscription_value.get(
                    "status"
                )
                or ""
            ) == "awaiting_invoice"
            and not invoice_value
            and ready
        )

        return {
            "periods":
                list(
                    BILLING_PERIOD_MONTHS
                ),
            "subscription":
                subscription_value,
            "invoice":
                invoice_value,
            "payment_proof":
                proof_value,
            "supplier_ready":
                ready,
            "can_issue":
                can_issue,
        }

    def invoice_for_subscription(
        self,
        subscription_id: int,
        *,
        include_cancelled: bool = False,
    ) -> dict[str, Any] | None:
        conn = self._connect()

        try:
            sql = (
                """SELECT *
                   FROM subscription_invoices
                   WHERE subscription_id=?"""
            )

            if not include_cancelled:
                sql += (
                    " AND status<>'cancelled'"
                )

            sql += (
                " ORDER BY id DESC LIMIT 1"
            )

            row = conn.execute(
                sql,
                (int(subscription_id),),
            ).fetchone()

            return (
                self._invoice_dict(row)
                if row
                else None
            )

        finally:
            conn.close()

    def create_invoice(
        self,
        subscription_id: int,
        months_count: int,
        actor_user_id: int,
        *,
        seller_snapshot: dict[str, Any],
        due_days: int = 5,
    ) -> dict[str, Any]:
        months = int(
            months_count
        )

        if months not in BILLING_PERIOD_MONTHS:
            raise SubscriptionError(
                "\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u044b "
                "\u043f\u0435\u0440\u0438\u043e\u0434\u044b "
                "\u043e\u043f\u043b\u0430\u0442\u044b: "
                "1, 2, 3, 6 "
                "\u0438\u043b\u0438 12 "
                "\u043c\u0435\u0441\u044f\u0446\u0435\u0432."
            )

        payment_days = int(
            due_days
        )

        if not 1 <= payment_days <= 90:
            raise SubscriptionError(
                "\u0421\u0440\u043e\u043a "
                "\u043e\u043f\u043b\u0430\u0442\u044b "
                "\u0441\u0447\u0451\u0442\u0430 "
                "\u0434\u043e\u043b\u0436\u0435\u043d "
                "\u0431\u044b\u0442\u044c "
                "\u043e\u0442 1 "
                "\u0434\u043e 90 "
                "\u0434\u043d\u0435\u0439."
            )

        seller = dict(
            seller_snapshot
            or {}
        )

        if not str(
            seller.get("name")
            or ""
        ).strip():
            raise SubscriptionError(
                "\u041d\u0435 "
                "\u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u044b "
                "\u0440\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b "
                "\u043f\u043e\u0441\u0442\u0430\u0432\u0449\u0438\u043a\u0430."
            )

        vat_rate = float(
            seller.get(
                "vat_rate",
                0,
            )
            or 0
        )

        if not 0 <= vat_rate <= 100:
            raise SubscriptionError(
                "\u0421\u0442\u0430\u0432\u043a\u0430 "
                "\u041d\u0414\u0421 "
                "\u0434\u043e\u043b\u0436\u043d\u0430 "
                "\u0431\u044b\u0442\u044c "
                "\u043e\u0442 0 "
                "\u0434\u043e 100."
            )

        conn = self._connect()

        try:
            if not isinstance(
                conn,
                PostgresConnection,
            ):
                conn.execute(
                    "BEGIN IMMEDIATE"
                )

            query = (
                """SELECT
                       s.*,
                       p.code AS plan_code,
                       p.name AS plan_name,
                       t.name AS tenant_name,
                       t.registration_number
                           AS tenant_registration_number,
                       t.contact_email
                           AS tenant_contact_email,
                       t.contact_phone
                           AS tenant_contact_phone,
                       t.legal_address
                           AS tenant_legal_address,
                       t.actual_address
                           AS tenant_actual_address,
                       t.status AS tenant_status
                   FROM tenant_subscriptions s
                   JOIN subscription_plans p
                     ON p.id=s.plan_id
                   JOIN tenants t
                     ON t.id=s.tenant_id
                   WHERE s.id=?"""
            )

            if isinstance(
                conn,
                PostgresConnection,
            ):
                query += " FOR UPDATE"

            row = conn.execute(
                query,
                (int(subscription_id),),
            ).fetchone()

            if not row:
                raise SubscriptionError(
                    "\u0417\u0430\u044f\u0432\u043a\u0430 "
                    "\u043d\u0430 "
                    "\u043f\u0430\u043a\u0435\u0442 "
                    "\u043d\u0435 "
                    "\u043d\u0430\u0439\u0434\u0435\u043d\u0430."
                )

            existing = conn.execute(
                """SELECT *
                   FROM subscription_invoices
                   WHERE subscription_id=?
                     AND status<>'cancelled'
                   ORDER BY id DESC
                   LIMIT 1""",
                (int(subscription_id),),
            ).fetchone()

            if existing:
                if (
                    str(
                        existing["status"]
                    ) == "issued"
                    and int(
                        existing["months_count"]
                    ) == months
                ):
                    conn.commit()
                    return self._invoice_dict(
                        existing
                    )

                raise SubscriptionError(
                    "\u0414\u043b\u044f "
                    "\u044d\u0442\u043e\u0439 "
                    "\u0437\u0430\u044f\u0432\u043a\u0438 "
                    "\u0443\u0436\u0435 "
                    "\u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442 "
                    "\u0434\u0435\u0439\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439 "
                    "\u0441\u0447\u0451\u0442. "
                    "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 "
                    "\u043e\u0442\u043c\u0435\u043d\u0438\u0442\u0435 "
                    "\u0435\u0433\u043e."
                )

            if str(
                row["status"]
            ) != "awaiting_invoice":
                raise SubscriptionError(
                    "\u0421\u0447\u0451\u0442 "
                    "\u043d\u0435\u043b\u044c\u0437\u044f "
                    "\u0441\u0444\u043e\u0440\u043c\u0438\u0440\u043e\u0432\u0430\u0442\u044c "
                    "\u0432 "
                    "\u0442\u0435\u043a\u0443\u0449\u0435\u043c "
                    "\u0441\u0442\u0430\u0442\u0443\u0441\u0435 "
                    "\u043f\u0430\u043a\u0435\u0442\u0430."
                )

            if str(
                row["tenant_status"]
            ) not in {
                "approved",
                "active",
            }:
                raise SubscriptionError(
                    "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 "
                    "\u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e "
                    "\u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0434\u0438\u0442\u044c "
                    "\u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044e."
                )

            if str(
                row["plan_code"]
            ).casefold() == "trial":
                raise SubscriptionError(
                    "\u0414\u043b\u044f Trial "
                    "\u0441\u0447\u0451\u0442 "
                    "\u043d\u0435 "
                    "\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f."
                )

            unit_price = round(
                float(
                    row["price_amount"]
                ),
                2,
            )

            if unit_price <= 0:
                raise SubscriptionError(
                    "\u0421\u0443\u043c\u043c\u0430 "
                    "\u043f\u043b\u0430\u0442\u043d\u043e\u0433\u043e "
                    "\u043f\u0430\u043a\u0435\u0442\u0430 "
                    "\u0434\u043e\u043b\u0436\u043d\u0430 "
                    "\u0431\u044b\u0442\u044c "
                    "\u0431\u043e\u043b\u044c\u0448\u0435 "
                    "\u043d\u0443\u043b\u044f."
                )

            total = round(
                unit_price * months,
                2,
            )

            vat_amount = (
                round(
                    total
                    * vat_rate
                    / (
                        100
                        + vat_rate
                    ),
                    2,
                )
                if vat_rate > 0
                else 0.0
            )

            subtotal = round(
                total - vat_amount,
                2,
            )

            buyer = {
                "name":
                    str(
                        row["tenant_name"]
                        or ""
                    ),
                "registration_number":
                    str(
                        row[
                            "tenant_registration_number"
                        ]
                        or ""
                    ),
                "email":
                    str(
                        row[
                            "tenant_contact_email"
                        ]
                        or ""
                    ),
                "phone":
                    str(
                        row[
                            "tenant_contact_phone"
                        ]
                        or ""
                    ),
                "legal_address":
                    str(
                        row[
                            "tenant_legal_address"
                        ]
                        or ""
                    ),
                "actual_address":
                    str(
                        row[
                            "tenant_actual_address"
                        ]
                        or ""
                    ),
            }

            line_items = [
                {
                    "service_code":
                        "subscription",
                    "plan_code":
                        str(
                            row["plan_code"]
                            or ""
                        ),
                    "plan_name":
                        str(
                            row["plan_name"]
                            or row["plan_code"]
                            or ""
                        ),
                    "name":
                        (
                            "Spyon - "
                            + str(
                                row["plan_name"]
                                or row["plan_code"]
                                or ""
                            )
                        ),
                    "quantity":
                        months,
                    "unit_code":
                        "month",
                    "unit_label":
                        "\u043c\u0435\u0441.",
                    "unit_price":
                        unit_price,
                    "amount":
                        total,
                }
            ]

            now = datetime.now().astimezone()

            stamp = now.isoformat(
                timespec="seconds"
            )

            due_at = (
                now
                + timedelta(
                    days=payment_days
                )
            ).isoformat(
                timespec="seconds"
            )

            invoice_number = (
                self._next_invoice_number(
                    conn,
                    now,
                )
            )

            conn.execute(
                """INSERT INTO subscription_invoices(
                       tenant_id,
                       subscription_id,
                       invoice_number,
                       status,
                       months_count,
                       unit_price,
                       subtotal_amount,
                       vat_rate,
                       vat_amount,
                       total_amount,
                       currency,
                       seller_snapshot_json,
                       buyer_snapshot_json,
                       line_items_json,
                       issued_at,
                       due_at,
                       pdf_path,
                       pdf_sha256,
                       created_by,
                       created_at,
                       updated_at
                   )
                   VALUES(
                       ?,?,?,?,?,?,?,?,?,?,?,
                       ?,?,?,?,?,?,?,?,?,?
                   )""",
                (
                    int(row["tenant_id"]),
                    int(subscription_id),
                    invoice_number,
                    "issued",
                    months,
                    unit_price,
                    subtotal,
                    vat_rate,
                    vat_amount,
                    total,
                    str(
                        row["currency"]
                        or "KZT"
                    ),
                    json.dumps(
                        seller,
                        ensure_ascii=False,
                        default=str,
                    ),
                    json.dumps(
                        buyer,
                        ensure_ascii=False,
                        default=str,
                    ),
                    json.dumps(
                        line_items,
                        ensure_ascii=False,
                        default=str,
                    ),
                    stamp,
                    due_at,
                    "",
                    "",
                    int(actor_user_id),
                    stamp,
                    stamp,
                ),
            )

            conn.execute(
                """UPDATE tenant_subscriptions
                   SET status='awaiting_payment',
                       updated_at=?
                   WHERE id=?""",
                (
                    stamp,
                    int(subscription_id),
                ),
            )

            result = conn.execute(
                """SELECT *
                   FROM subscription_invoices
                   WHERE invoice_number=?""",
                (invoice_number,),
            ).fetchone()

            if not result:
                raise SubscriptionError(
                    "\u0421\u0447\u0451\u0442 "
                    "\u043d\u0435 "
                    "\u0441\u043e\u0445\u0440\u0430\u043d\u0451\u043d."
                )

            conn.commit()

            return self._invoice_dict(
                result
            )

        except Exception:
            conn.rollback()
            raise

        finally:
            conn.close()

    def cancel_invoice(
        self,
        invoice_id: int,
        actor_user_id: int,
        reason: str,
    ) -> dict[str, Any]:
        note = str(
            reason or ""
        ).strip()

        if len(note) < 3:
            raise SubscriptionError(
                "\u0423\u043a\u0430\u0436\u0438\u0442\u0435 "
                "\u043f\u0440\u0438\u0447\u0438\u043d\u0443 "
                "\u043e\u0442\u043c\u0435\u043d\u044b "
                "\u0441\u0447\u0451\u0442\u0430."
            )

        conn = self._connect()

        try:
            if not isinstance(
                conn,
                PostgresConnection,
            ):
                conn.execute(
                    "BEGIN IMMEDIATE"
                )

            query = (
                """SELECT *
                   FROM subscription_invoices
                   WHERE id=?"""
            )

            if isinstance(
                conn,
                PostgresConnection,
            ):
                query += " FOR UPDATE"

            invoice = conn.execute(
                query,
                (int(invoice_id),),
            ).fetchone()

            if not invoice:
                raise SubscriptionError(
                    "\u0421\u0447\u0451\u0442 "
                    "\u043d\u0435 "
                    "\u043d\u0430\u0439\u0434\u0435\u043d."
                )

            if str(
                invoice["status"]
            ) == "cancelled":
                conn.commit()
                return self._invoice_dict(
                    invoice
                )

            if str(
                invoice["status"]
            ) != "issued":
                raise SubscriptionError(
                    "\u042d\u0442\u043e\u0442 "
                    "\u0441\u0447\u0451\u0442 "
                    "\u0443\u0436\u0435 "
                    "\u043d\u0435\u043b\u044c\u0437\u044f "
                    "\u043e\u0442\u043c\u0435\u043d\u0438\u0442\u044c."
                )

            stamp = now_iso()

            conn.execute(
                """UPDATE subscription_invoices
                   SET status='cancelled',
                       cancelled_by=?,
                       cancelled_at=?,
                       cancel_reason=?,
                       updated_at=?
                   WHERE id=?""",
                (
                    int(actor_user_id),
                    stamp,
                    note,
                    stamp,
                    int(invoice_id),
                ),
            )

            conn.execute(
                """UPDATE tenant_subscriptions
                   SET status='awaiting_invoice',
                       updated_at=?
                   WHERE id=?
                     AND status='awaiting_payment'""",
                (
                    stamp,
                    int(
                        invoice[
                            "subscription_id"
                        ]
                    ),
                ),
            )

            conn.commit()

            result = conn.execute(
                """SELECT *
                   FROM subscription_invoices
                   WHERE id=?""",
                (int(invoice_id),),
            ).fetchone()

            return self._invoice_dict(
                result
            )

        except Exception:
            conn.rollback()
            raise

        finally:
            conn.close()
