"""Database-backed lifecycle for immutable published legal-document versions."""
from __future__ import annotations

from datetime import datetime, timezone
from hashlib import sha256
from html import escape
from pathlib import Path
from typing import Any

from markupsafe import Markup

from legal_documents import LEGAL_DOCUMENTS
from storage.postgres_compat import PostgresConnection, configure_connection, connect_database


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class LegalDocumentService:
    """Publishes immutable versions and records server-derived acceptances."""

    def __init__(self, db_path: Path) -> None:
        self.db_path = Path(db_path)
        self.ensure_schema()

    def _connect(self) -> Any:
        return configure_connection(
            connect_database(self.db_path, timeout=30), foreign_keys=True, busy_timeout=30000
        )

    def ensure_schema(self) -> None:
        conn = self._connect()
        try:
            if isinstance(conn, PostgresConnection):
                conn.execute("""CREATE TABLE IF NOT EXISTS legal_documents(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    document_type TEXT NOT NULL UNIQUE,document_number TEXT NOT NULL,title TEXT NOT NULL,
                    created_at TEXT NOT NULL,updated_at TEXT NOT NULL)""")
                conn.execute("""CREATE TABLE IF NOT EXISTS legal_document_versions(
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    document_id BIGINT NOT NULL REFERENCES legal_documents(id) ON DELETE CASCADE,
                    version TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',body_text TEXT NOT NULL DEFAULT '',
                    acceptance_text TEXT NOT NULL DEFAULT '',content_sha256 TEXT NOT NULL,
                    requires_acceptance INTEGER NOT NULL DEFAULT 1,created_by BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
                    created_at TEXT NOT NULL,published_by BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
                    published_at TEXT,archived_at TEXT,UNIQUE(document_id,version))""")
            else:
                conn.execute("""CREATE TABLE IF NOT EXISTS legal_documents(
                    id INTEGER PRIMARY KEY AUTOINCREMENT,document_type TEXT NOT NULL UNIQUE,
                    document_number TEXT NOT NULL,title TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)""")
                conn.execute("""CREATE TABLE IF NOT EXISTS legal_document_versions(
                    id INTEGER PRIMARY KEY AUTOINCREMENT,document_id INTEGER NOT NULL,version TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'draft',body_text TEXT NOT NULL DEFAULT '',
                    acceptance_text TEXT NOT NULL DEFAULT '',content_sha256 TEXT NOT NULL,
                    requires_acceptance INTEGER NOT NULL DEFAULT 1,created_by INTEGER,created_at TEXT NOT NULL,
                    published_by INTEGER,published_at TEXT,archived_at TEXT,UNIQUE(document_id,version),
                    FOREIGN KEY(document_id) REFERENCES legal_documents(id) ON DELETE CASCADE)""")
            conn.execute("CREATE INDEX IF NOT EXISTS idx_legal_versions_current ON legal_document_versions(document_id,status,published_at DESC,id DESC)")
            # SQLite-compatible old schemas need this nullable evidence link.
            if not isinstance(conn, PostgresConnection):
                columns = {str(row[1]) for row in conn.execute("PRAGMA table_info(legal_acceptances)")}
                if "legal_document_version_id" not in columns:
                    conn.execute("ALTER TABLE legal_acceptances ADD COLUMN legal_document_version_id INTEGER")
            self._seed_legacy_versions(conn)
            conn.commit()
        finally:
            conn.close()

    def _seed_legacy_versions(self, conn: Any) -> None:
        """Import existing v1.0 definitions once without invalidating consent."""
        stamp = now_iso()
        for definition in LEGAL_DOCUMENTS.current_documents():
            row = conn.execute("SELECT id FROM legal_documents WHERE document_type=?", (definition.document_type,)).fetchone()
            if row is None:
                cursor = conn.execute(
                    "INSERT INTO legal_documents(document_type,document_number,title,created_at,updated_at) VALUES(?,?,?,?,?)",
                    (definition.document_type, definition.number, definition.title, stamp, stamp),
                )
                document_id = int(cursor.lastrowid)
            else:
                document_id = int(row["id"])
            exists = conn.execute(
                "SELECT id FROM legal_document_versions WHERE document_id=? AND version=?",
                (document_id, definition.version),
            ).fetchone()
            if exists is None:
                body = "\n\n".join(
                    block.get("text", "") for block in LEGAL_DOCUMENTS.blocks(definition)
                    if block.get("text")
                )
                conn.execute(
                    """INSERT INTO legal_document_versions(document_id,version,status,body_text,acceptance_text,
                       content_sha256,requires_acceptance,created_at,published_at)
                       VALUES(?,?, 'published',?,?,?,?,?,?)""",
                    (document_id, definition.version, body, definition.acceptance_text,
                     LEGAL_DOCUMENTS.sha256(definition), 1, stamp, stamp),
                )

    @staticmethod
    def _metadata(row: dict[str, Any]) -> dict[str, Any]:
        return {
            "id": int(row["id"]), "type": str(row["document_type"]),
            "number": str(row["document_number"]), "title": str(row["title"]),
            "version": str(row["version"]), "status": str(row["status"]),
            "sha256": str(row["content_sha256"]),
            "requires_acceptance": bool(row["requires_acceptance"]),
            "published_at": row["published_at"], "created_at": row["created_at"],
            "legacy_static": str(row["version"]) == "1.0" and str(row["document_type"]) in {"offer", "privacy"},
        }

    def _version(self, conn: Any, document_type: str, version: str | None = None) -> dict[str, Any] | None:
        params: list[Any] = [str(document_type).strip().casefold()]
        where = "d.document_type=?"
        if version is None:
            where += " AND v.status='published'"
            order = "ORDER BY v.published_at DESC,v.id DESC LIMIT 1"
        else:
            where += " AND v.version=?"
            params.append(str(version).strip())
            order = "LIMIT 1"
        row = conn.execute(
            """SELECT v.*,d.document_type,d.document_number,d.title FROM legal_document_versions v
               JOIN legal_documents d ON d.id=v.document_id WHERE """ + where + " " + order,
            params,
        ).fetchone()
        return dict(row) if row else None

    def get_version(self, document_type: str, version: str | None = None) -> dict[str, Any] | None:
        conn = self._connect()
        try:
            row = self._version(conn, document_type, version)
            return ({**self._metadata(row), "body_text": str(row["body_text"]), "acceptance_text": str(row["acceptance_text"])} if row else None)
        finally:
            conn.close()

    def current_documents(self) -> list[dict[str, Any]]:
        result: list[dict[str, Any]] = []
        for document_type in ("offer", "privacy"):
            row = self.get_version(document_type)
            if row:
                result.append(row)
        return result

    def acceptance_records(self, *, ip_address: str, user_agent: str, locale: str, source: str = "registration") -> list[dict[str, Any]]:
        normalized_locale = str(locale or "ru").casefold()
        if normalized_locale not in {"ru", "kk", "en"}:
            normalized_locale = "ru"
        accepted_at = now_iso()
        return [{
            "legal_document_version_id": item["id"], "document_type": item["type"],
            "document_number": item["number"], "document_version": item["version"],
            "document_sha256": item["sha256"], "accepted_at": accepted_at,
            "ip_address": str(ip_address or "")[:128], "user_agent": str(user_agent or "")[:1024],
            "locale": normalized_locale, "acceptance_text": item["acceptance_text"], "source": source,
        } for item in self.current_documents() if item["requires_acceptance"]]

    def accepted_documents_for_user(self, user_id: int, tenant_id: int | None) -> list[dict[str, Any]]:
        conn = self._connect()
        try:
            result: list[dict[str, Any]] = []
            for document in self.current_documents():
                row = conn.execute(
                    """SELECT accepted_at FROM legal_acceptances WHERE user_id=? AND document_type=?
                       AND document_version=? ORDER BY accepted_at DESC LIMIT 1""",
                    (int(user_id), document["type"], document["version"]),
                ).fetchone()
                result.append({**document, "accepted_at": row["accepted_at"] if row else None, "tenant_id": tenant_id})
            return result
        finally:
            conn.close()

    def required_for_user(self, user_id: int, tenant_id: int | None) -> list[dict[str, Any]]:
        # v1.0 predates version lifecycle storage. It remains visible in the
        # history but must never suddenly lock out existing users merely
        # because their earlier consent was not recorded in this table.
        return [item for item in self.accepted_documents_for_user(user_id, tenant_id)
                if item["requires_acceptance"] and item["version"] != "1.0" and not item["accepted_at"]]

    def accept(self, user_id: int, tenant_id: int, document_type: str, *, ip_address: str, user_agent: str, locale: str) -> dict[str, Any]:
        document = self.get_version(document_type)
        if not document or not document["requires_acceptance"]:
            raise ValueError("Документ недоступен для принятия.")
        conn = self._connect()
        try:
            stamp = now_iso()
            conn.execute(
                """INSERT INTO legal_acceptances(legal_document_version_id,user_id,tenant_id,document_type,
                   document_number,document_version,document_sha256,accepted_at,ip_address,user_agent,locale,
                   acceptance_text,source,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(user_id,document_type,document_version) DO NOTHING""",
                (document["id"], int(user_id), int(tenant_id), document["type"], document["number"],
                 document["version"], document["sha256"], stamp, str(ip_address or "")[:128],
                 str(user_agent or "")[:1024], str(locale or "ru")[:16], document["acceptance_text"],
                 "settings", stamp),
            )
            conn.commit()
            return document
        finally:
            conn.close()

    def list_versions(self) -> list[dict[str, Any]]:
        conn = self._connect()
        try:
            rows = conn.execute("""SELECT v.*,d.document_type,d.document_number,d.title FROM legal_document_versions v
                JOIN legal_documents d ON d.id=v.document_id ORDER BY d.document_type,v.created_at DESC,v.id DESC""").fetchall()
            return [{**self._metadata(dict(row)), "body_text": str(row["body_text"]), "acceptance_text": str(row["acceptance_text"])} for row in rows]
        finally:
            conn.close()

    def acceptance_audit(self, version_id: int | None = None) -> list[dict[str, Any]]:
        conn = self._connect()
        try:
            where = "WHERE a.legal_document_version_id=?" if version_id else ""
            rows = conn.execute(
                """SELECT a.accepted_at,a.document_type,a.document_version,a.locale,a.source,
                          u.display_name,u.email,t.name AS tenant_name
                   FROM legal_acceptances a JOIN app_users u ON u.id=a.user_id
                   JOIN tenants t ON t.id=a.tenant_id """ + where +
                " ORDER BY a.accepted_at DESC LIMIT 500",
                ([int(version_id)] if version_id else []),
            ).fetchall()
            return [dict(row) for row in rows]
        finally:
            conn.close()

    def save_draft(self, payload: dict[str, Any], actor_user_id: int, version_id: int | None = None) -> dict[str, Any]:
        doc_type = str(payload.get("type") or "").strip().casefold()
        version = str(payload.get("version") or "").strip()
        number = str(payload.get("number") or "").strip()
        title = str(payload.get("title") or "").strip()
        body = str(payload.get("body_text") or "").strip()
        acceptance = str(payload.get("acceptance_text") or "").strip()
        if doc_type not in {"offer", "privacy"} or not version or not number or not title or not body or not acceptance:
            raise ValueError("Заполните тип, номер, версию, название, текст и формулировку принятия.")
        digest = sha256((doc_type + "\n" + number + "\n" + version + "\n" + title + "\n" + body + "\n" + acceptance).encode()).hexdigest()
        conn = self._connect()
        try:
            stamp = now_iso()
            if version_id:
                old = conn.execute("SELECT status FROM legal_document_versions WHERE id=?", (int(version_id),)).fetchone()
                if not old or old["status"] != "draft":
                    raise ValueError("Редактировать можно только черновик.")
                conn.execute("UPDATE legal_document_versions SET version=?,body_text=?,acceptance_text=?,content_sha256=? WHERE id=?",
                             (version, body, acceptance, digest, int(version_id)))
                conn.execute("UPDATE legal_documents SET document_number=?,title=?,updated_at=? WHERE id=(SELECT document_id FROM legal_document_versions WHERE id=?)",
                             (number, title, stamp, int(version_id)))
            else:
                doc = conn.execute("SELECT id FROM legal_documents WHERE document_type=?", (doc_type,)).fetchone()
                if doc is None:
                    cur = conn.execute("INSERT INTO legal_documents(document_type,document_number,title,created_at,updated_at) VALUES(?,?,?,?,?)", (doc_type, number, title, stamp, stamp))
                    document_id = int(cur.lastrowid)
                else:
                    document_id = int(doc["id"])
                cur = conn.execute("""INSERT INTO legal_document_versions(document_id,version,status,body_text,acceptance_text,
                    content_sha256,requires_acceptance,created_by,created_at) VALUES(?,?,'draft',?,?,?,?,?,?)""",
                    (document_id, version, body, acceptance, digest, 1, int(actor_user_id), stamp))
                version_id = int(cur.lastrowid)
            conn.commit()
        finally:
            conn.close()
        return self.get_version(doc_type, version) or {}

    def publish(self, version_id: int, actor_user_id: int) -> dict[str, Any]:
        conn = self._connect()
        try:
            row = conn.execute("SELECT v.*,d.document_type FROM legal_document_versions v JOIN legal_documents d ON d.id=v.document_id WHERE v.id=?", (int(version_id),)).fetchone()
            if not row or row["status"] != "draft":
                raise ValueError("Опубликовать можно только существующий черновик.")
            stamp = now_iso()
            conn.execute("UPDATE legal_document_versions SET status='archived',archived_at=? WHERE document_id=? AND status='published'", (stamp, int(row["document_id"])))
            conn.execute("UPDATE legal_document_versions SET status='published',published_by=?,published_at=? WHERE id=?", (int(actor_user_id), stamp, int(version_id)))
            conn.commit()
            return self.get_version(str(row["document_type"]), str(row["version"])) or {}
        finally:
            conn.close()

    @staticmethod
    def html(document: dict[str, Any]) -> Markup:
        return Markup("\n".join(f"<p>{escape(part)}</p>" for part in str(document.get("body_text") or "").split("\n\n") if part.strip()))
