from __future__ import annotations

import math
import threading
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

from storage.postgres_compat import PostgresConnection, configure_connection, connect_database


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _parse_time(value: Any) -> datetime | None:
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed.astimezone() if parsed.tzinfo else parsed.astimezone()


class NotificationService:
    """Persistent per-user notifications backed by the application database."""

    def __init__(self, db_path: Path, email_service: Any | None = None):
        self.db_path = Path(db_path)
        self.email_service = email_service
        self._cache_lock = threading.Lock()
        self._task_states: dict[str, str] = {}
        self._expiry_checks: dict[int, float] = {}
        self.ensure_schema()

    def set_email_service(self, email_service: Any | None) -> None:
        """Attach the optional transactional-email channel after app startup."""
        self.email_service = email_service

    def _connect(self) -> PostgresConnection | Any:
        conn = connect_database(self.db_path, timeout=30)
        return configure_connection(conn, foreign_keys=True, busy_timeout=30000)

    def ensure_schema(self) -> None:
        conn = self._connect()
        try:
            if isinstance(conn, PostgresConnection):
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS app_notifications(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE,
                           user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
                           category TEXT NOT NULL DEFAULT 'system',
                           event_type TEXT NOT NULL,
                           level TEXT NOT NULL DEFAULT 'info',
                           title TEXT NOT NULL,
                           message TEXT NOT NULL DEFAULT '',
                           action_url TEXT NOT NULL DEFAULT '',
                           dedupe_key TEXT NOT NULL UNIQUE,
                           created_at TEXT NOT NULL,
                           read_at TEXT
                       )"""
                )
            else:
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS app_notifications(
                           id INTEGER PRIMARY KEY AUTOINCREMENT,
                           tenant_id INTEGER,
                           user_id INTEGER NOT NULL,
                           category TEXT NOT NULL DEFAULT 'system',
                           event_type TEXT NOT NULL,
                           level TEXT NOT NULL DEFAULT 'info',
                           title TEXT NOT NULL,
                           message TEXT NOT NULL DEFAULT '',
                           action_url TEXT NOT NULL DEFAULT '',
                           dedupe_key TEXT NOT NULL UNIQUE,
                           created_at TEXT NOT NULL,
                           read_at TEXT,
                           FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
                           FOREIGN KEY(user_id) REFERENCES app_users(id) ON DELETE CASCADE
                       )"""
                )
            conn.execute(
                """CREATE INDEX IF NOT EXISTS idx_app_notifications_user_time
                   ON app_notifications(user_id,created_at DESC)"""
            )
            conn.execute(
                """CREATE INDEX IF NOT EXISTS idx_app_notifications_unread
                   ON app_notifications(user_id,read_at,created_at DESC)"""
            )
            conn.commit()
        finally:
            conn.close()

    def create(
        self,
        *,
        tenant_id: int | None,
        user_id: int,
        category: str,
        event_type: str,
        title: str,
        message: str = "",
        level: str = "info",
        action_url: str = "/app",
        dedupe_key: str,
    ) -> None:
        row = (
            tenant_id, int(user_id), str(category), str(event_type), str(level),
            str(title)[:240], str(message)[:1200], str(action_url)[:500],
            str(dedupe_key)[:500], now_iso(),
        )
        self._insert_many([row])

    def _insert_many(self, rows: list[tuple[Any, ...]]) -> None:
        if not rows:
            return
        conn = self._connect()
        try:
            conn.executemany(
                """INSERT INTO app_notifications(
                       tenant_id,user_id,category,event_type,level,title,message,
                       action_url,dedupe_key,created_at
                   ) VALUES(?,?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(dedupe_key) DO NOTHING""",
                rows,
            )
            conn.commit()
        finally:
            conn.close()
        channel = self.email_service
        if channel is not None:
            for row in rows:
                preferences = self.preferences_for_user(int(row[1]))
                category = str(row[2])
                if not preferences.get(category, {}).get("email_enabled", True):
                    continue
                try:
                    channel.queue_notification(
                        tenant_id=int(row[0]) if row[0] is not None else None,
                        user_id=int(row[1]), category=str(row[2]), event_type=str(row[3]),
                        title=str(row[5]), message=str(row[6]), action_url=str(row[7]),
                        dedupe_key=str(row[8]),
                    )
                except Exception:
                    # Notification delivery is deliberately best effort: an email
                    # configuration or provider outage must not break in-app work.
                    pass

    def preferences_for_user(self, user_id: int) -> dict[str, dict[str, bool]]:
        defaults = {
            category: {
                "in_app_enabled": True, "email_enabled": True,
                "telegram_enabled": True,
            }
            for category in ("security", "billing", "marketplaces", "operations")
        }
        conn = self._connect()
        try:
            rows = conn.execute(
                """SELECT category,in_app_enabled,email_enabled,telegram_enabled
                   FROM notification_preferences WHERE user_id=?""",
                (int(user_id),),
            ).fetchall()
        finally:
            conn.close()
        for row in rows:
            category = str(row["category"])
            if category not in defaults:
                continue
            defaults[category] = {
                "in_app_enabled": bool(row["in_app_enabled"]),
                "email_enabled": bool(row["email_enabled"]),
                "telegram_enabled": bool(row["telegram_enabled"]),
            }
        # Security delivery is a required account-protection channel.
        defaults["security"] = {
            "in_app_enabled": True, "email_enabled": True,
            "telegram_enabled": True,
        }
        return defaults

    def save_preferences(
        self, user_id: int, values: dict[str, Any]
    ) -> dict[str, dict[str, bool]]:
        if not isinstance(values, dict):
            raise ValueError("Настройки уведомлений должны быть объектом.")
        stamp = now_iso()
        conn = self._connect()
        try:
            for category in ("security", "billing", "marketplaces", "operations"):
                raw = values.get(category)
                if not isinstance(raw, dict):
                    continue
                if category == "security":
                    in_app, email, telegram = 1, 1, 1
                else:
                    in_app = 1 if raw.get("in_app_enabled", True) else 0
                    email = 1 if raw.get("email_enabled", True) else 0
                    telegram = 1 if raw.get("telegram_enabled", True) else 0
                conn.execute(
                    """INSERT INTO notification_preferences(
                           user_id,category,in_app_enabled,email_enabled,telegram_enabled,
                           created_at,updated_at
                       ) VALUES(?,?,?,?,?,?,?)
                       ON CONFLICT(user_id,category) DO UPDATE SET
                           in_app_enabled=excluded.in_app_enabled,
                           email_enabled=excluded.email_enabled,
                           telegram_enabled=excluded.telegram_enabled,
                           updated_at=excluded.updated_at""",
                    (int(user_id), category, in_app, email, telegram, stamp, stamp),
                )
            conn.commit()
        finally:
            conn.close()
        return self.preferences_for_user(int(user_id))

    def sync_tasks(self, tasks: Iterable[dict[str, Any]]) -> None:
        rows: list[tuple[Any, ...]] = []
        stamp = now_iso()
        task_items = list(tasks)[:75]
        for task in task_items:
            metadata = task.get("metadata") if isinstance(task.get("metadata"), dict) else {}
            user_id = metadata.get("requested_by_id")
            if not user_id:
                continue
            tenant_id = metadata.get("tenant_id")
            status = str(task.get("status") or "")
            task_id = str(task.get("id") or "")
            label = str(task.get("label") or task.get("name") or "Операция")
            if not task_id:
                continue
            with self._cache_lock:
                if self._task_states.get(task_id) == status:
                    continue
            if status == "queued":
                title, message, level = "Операция поставлена в очередь", label, "info"
            elif status == "running":
                title, message, level = "Синхронизация запущена", label, "info"
            elif status == "completed":
                title, message, level = "Синхронизация завершена", label, "success"
            elif status in {"failed", "interrupted", "stopped"}:
                title = "Ошибка синхронизации" if status == "failed" else "Синхронизация остановлена"
                message = f"{label}. {str(task.get('message') or '').strip()}".strip()
                level = "danger" if status == "failed" else "warning"
            else:
                continue
            rows.append((
                int(tenant_id) if tenant_id is not None else None,
                int(user_id), "operations", f"task_{status}", level,
                title[:240], message[:1200], "/app#operations",
                f"task:{task_id}:{status}:user:{int(user_id)}", stamp,
            ))
        self._insert_many(rows)
        with self._cache_lock:
            for task in task_items:
                task_id = str(task.get("id") or "")
                status = str(task.get("status") or "")
                if task_id and status:
                    self._task_states[task_id] = status
            if len(self._task_states) > 2000:
                self._task_states = dict(list(self._task_states.items())[-1000:])

    def ensure_expiry_reminders(self, tenant_id: int | None) -> None:
        if not tenant_id:
            return
        tenant_key = int(tenant_id)
        current_tick = time.monotonic()
        with self._cache_lock:
            if current_tick - self._expiry_checks.get(tenant_key, 0.0) < 300:
                return
        conn = self._connect()
        try:
            row = conn.execute(
                """SELECT s.id,s.ends_at,p.name plan_name
                   FROM tenant_subscriptions s
                   JOIN subscription_plans p ON p.id=s.plan_id
                   WHERE s.tenant_id=? AND s.status='active'
                   ORDER BY s.id DESC LIMIT 1""",
                (int(tenant_id),),
            ).fetchone()
            users = [int(item[0]) for item in conn.execute(
                """SELECT u.id FROM tenant_users tu JOIN app_users u ON u.id=tu.user_id
                   WHERE tu.tenant_id=? AND tu.is_active=1 AND u.is_active=1""",
                (int(tenant_id),),
            ).fetchall()]
        finally:
            conn.close()
        if not row:
            with self._cache_lock:
                self._expiry_checks[tenant_key] = current_tick
            return
        ends = _parse_time(row["ends_at"])
        if not ends:
            return
        seconds = (ends - datetime.now().astimezone()).total_seconds()
        remaining = max(0, int(math.ceil(seconds / 86400)))
        if seconds < 0 or remaining > 5:
            return
        day_key = datetime.now().astimezone().date().isoformat()
        title = "Пакет заканчивается сегодня" if remaining == 0 else f"Пакет заканчивается через {remaining} дн."
        message = f"Пакет «{row['plan_name']}» действует до {ends.strftime('%d.%m.%Y %H:%M')}. Подтвердите продление."
        self._insert_many([
            (
                int(tenant_id), user_id, "billing", "subscription_expiry", "warning",
                title[:240], message[:1200], "/app#settings",
                f"subscription:{int(row['id'])}:expiry:{day_key}:user:{user_id}", now_iso(),
            )
            for user_id in users
        ])
        with self._cache_lock:
            self._expiry_checks[tenant_key] = current_tick

    def list_for_user(self, user_id: int, limit: int = 50) -> dict[str, Any]:
        conn = self._connect()
        try:
            items = [dict(row) for row in conn.execute(
                """SELECT n.id,n.tenant_id,n.user_id,n.category,n.event_type,n.level,
                          n.title,n.message,n.action_url,n.created_at,n.read_at
                   FROM app_notifications n
                   LEFT JOIN notification_preferences p
                     ON p.user_id=n.user_id AND p.category=n.category
                   WHERE n.user_id=?
                     AND (n.category='security' OR COALESCE(p.in_app_enabled,1)=1)
                   ORDER BY n.id DESC LIMIT ?""",
                (int(user_id), max(1, min(int(limit), 200))),
            ).fetchall()]
            unread = int(conn.execute(
                """SELECT COUNT(*) FROM app_notifications n
                   LEFT JOIN notification_preferences p
                     ON p.user_id=n.user_id AND p.category=n.category
                   WHERE n.user_id=? AND n.read_at IS NULL
                     AND (n.category='security' OR COALESCE(p.in_app_enabled,1)=1)""",
                (int(user_id),),
            ).fetchone()[0])
            return {"items": items, "unread": unread}
        finally:
            conn.close()

    def mark_read(self, user_id: int, notification_id: int | None = None) -> int:
        conn = self._connect()
        try:
            stamp = now_iso()
            if notification_id is None:
                cursor = conn.execute(
                    "UPDATE app_notifications SET read_at=? WHERE user_id=? AND read_at IS NULL",
                    (stamp, int(user_id)),
                )
            else:
                cursor = conn.execute(
                    """UPDATE app_notifications SET read_at=?
                       WHERE id=? AND user_id=? AND read_at IS NULL""",
                    (stamp, int(notification_id), int(user_id)),
                )
            conn.commit()
            return max(0, int(cursor.rowcount))
        finally:
            conn.close()
