from __future__ import annotations

import json
import re
import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any
from storage.postgres_compat import PostgresConnection, connect_database, integrity_error_types

from marketplace_registry import MARKETPLACE_CODES


FEATURES = (
    ("products", "Каталог и товары", "Доступ к каталогу компании", "core"),
    ("operations", "Запуск операций", "Ручные операции сборщиков", "core"),
    ("reports", "Отчёты", "Формирование и выгрузка отчётов", "core"),
    ("schedules", "Расписания", "Автоматические запуски по расписанию", "automation"),
    ("dynamic_filters", "Динамические фильтры", "Фильтры по характеристикам каталога", "analytics"),
    ("team_management", "Пользователи", "Управление сотрудниками и правами", "core"),
)

DEFAULT_PLANS = (
    {
        "code": "trial", "name": "Пробный", "description": "Один бесплатный пробный период на 3 дня",
        "price_amount": 0, "term_days": 3, "daily_operation_limit": 3,
        "position_limit": 25, "display_order": 1,
        "disabled_features": {"schedules", "dynamic_filters", "team_management"},
    },
    {
        "code": "starter", "name": "Старт", "description": "До 100 позиций на площадку",
        "price_amount": 14900, "term_days": 30, "daily_operation_limit": 10,
        "position_limit": 100, "display_order": 10,
        "disabled_features": {"schedules"},
    },
    {
        "code": "growth", "name": "Рост", "description": "До 500 позиций на площадку",
        "price_amount": 39900, "term_days": 30, "daily_operation_limit": 50,
        "position_limit": 500, "display_order": 20, "disabled_features": set(),
    },
    {
        "code": "business", "name": "Бизнес", "description": "До 1 000 позиций на площадку",
        "price_amount": 89900, "term_days": 30, "daily_operation_limit": None,
        "position_limit": 1000, "display_order": 30, "disabled_features": set(),
    },
)

DEFAULT_ADDONS = (
    ("positions_100", "+100 позиций", 100, 5000, 10),
    ("positions_500", "+500 позиций", 500, 18000, 20),
    ("positions_1000", "+1 000 позиций", 1000, 30000, 30),
)


class SubscriptionError(ValueError):
    pass


class SubscriptionLimitError(SubscriptionError):
    pass


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _parse_time(value: Any) -> datetime | None:
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.astimezone()
    return parsed


def _optional_limit(value: Any, *, maximum: int = 10_000_000) -> int | None:
    if value in (None, "", "unlimited"):
        return None
    number = int(value)
    if number < 0 or number > maximum:
        raise SubscriptionError(f"Лимит должен быть от 0 до {maximum} или пустым для безлимита.")
    return number


class SubscriptionService:
    def __init__(self, db_path: Path):
        self.db_path = Path(db_path)
        self.ensure_payment_schema()
        self.ensure_seed_data()

    def _connect(self) -> sqlite3.Connection:
        conn = connect_database(self.db_path, timeout=30)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys=ON")
        conn.execute("PRAGMA busy_timeout=30000")
        return conn

    def ensure_payment_schema(self) -> None:
        conn = self._connect()
        try:
            if isinstance(conn, PostgresConnection):
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS subscription_payments(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
                           subscription_id BIGINT NOT NULL UNIQUE REFERENCES tenant_subscriptions(id) ON DELETE CASCADE,
                           amount DOUBLE PRECISION NOT NULL DEFAULT 0,
                           currency TEXT NOT NULL DEFAULT 'KZT',status TEXT NOT NULL DEFAULT 'confirmed',
                           paid_at TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,
                           term_days INTEGER NOT NULL,months_count DOUBLE PRECISION NOT NULL DEFAULT 1,
                           confirmed_by BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
                           note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL
                       )"""
                )
            else:
                conn.execute(
                    """CREATE TABLE IF NOT EXISTS subscription_payments(
                           id INTEGER PRIMARY KEY AUTOINCREMENT,tenant_id INTEGER NOT NULL,
                           subscription_id INTEGER NOT NULL UNIQUE,amount REAL NOT NULL DEFAULT 0,
                           currency TEXT NOT NULL DEFAULT 'KZT',status TEXT NOT NULL DEFAULT 'confirmed',
                           paid_at TEXT NOT NULL,period_start TEXT NOT NULL,period_end TEXT NOT NULL,
                           term_days INTEGER NOT NULL,months_count REAL NOT NULL DEFAULT 1,
                           confirmed_by INTEGER,note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,
                           FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
                           FOREIGN KEY(subscription_id) REFERENCES tenant_subscriptions(id) ON DELETE CASCADE,
                           FOREIGN KEY(confirmed_by) REFERENCES app_users(id) ON DELETE SET NULL
                       )"""
                )
            conn.execute(
                """CREATE INDEX IF NOT EXISTS idx_subscription_payments_time
                   ON subscription_payments(paid_at DESC,tenant_id)"""
            )
            conn.commit()
        finally:
            conn.close()

    @staticmethod
    def _plan_row(conn: sqlite3.Connection, plan_id: int) -> dict[str, Any]:
        row = conn.execute("SELECT * FROM subscription_plans WHERE id=?", (int(plan_id),)).fetchone()
        if not row:
            raise SubscriptionError("Пакет не найден.")
        value = dict(row)
        features = [dict(item) for item in conn.execute(
            """SELECT pf.feature_code,pf.is_enabled,pf.limit_value,pf.config_json,
                      f.name,f.description,f.category
               FROM subscription_plan_features pf
               JOIN subscription_features f ON f.code=pf.feature_code
               WHERE pf.plan_id=? ORDER BY f.category,f.name""",
            (int(plan_id),),
        ).fetchall()]
        for item in features:
            try:
                item["config"] = json.loads(str(item.pop("config_json") or "{}"))
            except json.JSONDecodeError:
                item["config"] = {}
            item["is_enabled"] = bool(item["is_enabled"])
        limits = [dict(item) for item in conn.execute(
            """SELECT marketplace_code,is_enabled,position_limit,daily_operation_limit
               FROM subscription_plan_marketplace_limits
               WHERE plan_id=? ORDER BY marketplace_code""",
            (int(plan_id),),
        ).fetchall()]
        for item in limits:
            item["is_enabled"] = bool(item["is_enabled"])
        value.update({
            "is_public": bool(value["is_public"]),
            "is_active": bool(value["is_active"]),
            "features": features,
            "marketplaces": limits,
        })
        return value

    def ensure_seed_data(self) -> None:
        conn = self._connect()
        try:
            stamp = now_iso()
            for code, name, description, category in FEATURES:
                conn.execute(
                    """INSERT INTO subscription_features(
                           code,name,description,category,is_active,created_at,updated_at
                       ) VALUES(?,?,?,?,1,?,?)
                       ON CONFLICT(code) DO UPDATE SET name=excluded.name,
                           description=excluded.description,category=excluded.category,
                           updated_at=excluded.updated_at""",
                    (code, name, description, category, stamp, stamp),
                )
            for marketplace in sorted(MARKETPLACE_CODES):
                code = f"marketplace.{marketplace}"
                conn.execute(
                    """INSERT INTO subscription_features(
                           code,name,description,category,is_active,created_at,updated_at
                       ) VALUES(?,?,?,'marketplaces',1,?,?)
                       ON CONFLICT(code) DO UPDATE SET updated_at=excluded.updated_at""",
                    (code, marketplace, "Доступ к площадке", stamp, stamp),
                )
            conn.execute(
                """INSERT INTO subscription_plans(
                       code,name,description,price_amount,currency,term_days,
                       daily_operation_limit,position_limit,is_public,is_active,
                       display_order,created_at,updated_at
                   ) VALUES('legacy','Legacy','Совместимость для действующих компаний',
                            0,'KZT',36500,NULL,NULL,0,1,9990,?,?)
                   ON CONFLICT(code) DO NOTHING""",
                (stamp, stamp),
            )
            legacy_id = int(conn.execute(
                "SELECT id FROM subscription_plans WHERE code='legacy'"
            ).fetchone()[0])
            for feature in [item[0] for item in FEATURES] + [
                f"marketplace.{code}" for code in sorted(MARKETPLACE_CODES)
            ]:
                conn.execute(
                    """INSERT INTO subscription_plan_features(plan_id,feature_code,is_enabled)
                       VALUES(?,?,1) ON CONFLICT(plan_id,feature_code) DO NOTHING""",
                    (legacy_id, feature),
                )
            for definition in DEFAULT_PLANS:
                conn.execute(
                    """INSERT INTO subscription_plans(
                           code,name,description,price_amount,currency,term_days,
                           daily_operation_limit,position_limit,is_public,is_active,
                           display_order,created_at,updated_at
                       ) VALUES(?,?,?,?, 'KZT',?,?,?,?,1,?,?,?)
                       ON CONFLICT(code) DO NOTHING""",
                    (
                        definition["code"], definition["name"], definition["description"],
                        definition["price_amount"], definition["term_days"],
                        definition["daily_operation_limit"], definition["position_limit"],
                        1, definition["display_order"], stamp, stamp,
                    ),
                )
                plan_id = int(conn.execute(
                    "SELECT id FROM subscription_plans WHERE code=?", (definition["code"],)
                ).fetchone()[0])
                for feature in [item[0] for item in FEATURES] + [
                    f"marketplace.{code}" for code in sorted(MARKETPLACE_CODES)
                ]:
                    enabled = feature not in definition["disabled_features"]
                    conn.execute(
                        """INSERT INTO subscription_plan_features(plan_id,feature_code,is_enabled)
                           VALUES(?,?,?) ON CONFLICT(plan_id,feature_code) DO NOTHING""",
                        (plan_id, feature, int(enabled)),
                    )
                for marketplace in sorted(MARKETPLACE_CODES):
                    conn.execute(
                        """INSERT INTO subscription_plan_marketplace_limits(
                               plan_id,marketplace_code,is_enabled,position_limit,daily_operation_limit
                           ) VALUES(?,?,1,?,?)
                           ON CONFLICT(plan_id,marketplace_code) DO NOTHING""",
                        (
                            plan_id, marketplace, definition["position_limit"],
                            definition["daily_operation_limit"],
                        ),
                    )
            for code, name, positions, price, order in DEFAULT_ADDONS:
                conn.execute(
                    """INSERT INTO subscription_addons(
                           code,name,description,extra_positions,price_amount,currency,
                           is_public,is_active,display_order,created_at,updated_at
                       ) VALUES(?,?,?, ?,?,'KZT',1,1,?,?,?)
                       ON CONFLICT(code) DO NOTHING""",
                    (code, name, "Дополнительная ёмкость каталога", positions, price, order, stamp, stamp),
                )
            # Existing approved workspaces keep their current behaviour until
            # an administrator explicitly assigns a commercial package.
            for tenant in conn.execute(
                """SELECT id,created_at FROM tenants t WHERE status IN ('active','approved','confirmed')
                   AND NOT EXISTS(SELECT 1 FROM tenant_subscriptions s WHERE s.tenant_id=t.id)"""
            ).fetchall():
                start = str(tenant["created_at"] or stamp)
                end = (datetime.now().astimezone() + timedelta(days=36500)).isoformat(timespec="seconds")
                snapshot = json.dumps(self._plan_row(conn, legacy_id), ensure_ascii=False, default=str)
                conn.execute(
                    """INSERT INTO tenant_subscriptions(
                           tenant_id,plan_id,status,requested_at,reviewed_at,starts_at,ends_at,
                           price_amount,currency,term_days,plan_snapshot_json,review_note,
                           created_at,updated_at
                       ) VALUES(?,?,'active',?,?,?,?,0,'KZT',36500,?,'Автоматическая миграция',?,?)""",
                    (int(tenant["id"]), legacy_id, start, stamp, start, end, snapshot, stamp, stamp),
                )
            conn.commit()
        finally:
            conn.close()

    def plans(self, *, public_only: bool = False) -> list[dict[str, Any]]:
        conn = self._connect()
        try:
            where = "WHERE is_active=1 AND is_public=1" if public_only else ""
            ids = [int(row[0]) for row in conn.execute(
                f"SELECT id FROM subscription_plans {where} ORDER BY display_order,name"
            ).fetchall()]
            return [self._plan_row(conn, plan_id) for plan_id in ids]
        finally:
            conn.close()

    def addons(self, *, public_only: bool = False) -> list[dict[str, Any]]:
        conn = self._connect()
        try:
            where = "WHERE is_active=1 AND is_public=1" if public_only else ""
            return [dict(row) for row in conn.execute(
                f"SELECT * FROM subscription_addons {where} ORDER BY display_order,name"
            ).fetchall()]
        finally:
            conn.close()

    def save_plan(self, payload: dict[str, Any], actor_user_id: int) -> dict[str, Any]:
        plan_id = int(payload.get("id") or 0)
        code = str(payload.get("code") or "").strip().casefold()
        name = str(payload.get("name") or "").strip()
        if not re.fullmatch(r"[a-z][a-z0-9_-]{1,39}", code):
            raise SubscriptionError("Код пакета: 2–40 латинских символов, цифр, _ или -.")
        if len(name) < 2:
            raise SubscriptionError("Укажите название пакета.")
        price = float(payload.get("price_amount") or 0)
        term_days = int(payload.get("term_days") or 30)
        if price < 0 or not 1 <= term_days <= 3650:
            raise SubscriptionError("Проверьте цену и срок пакета.")
        daily_limit = _optional_limit(payload.get("daily_operation_limit"), maximum=100000)
        position_limit = _optional_limit(payload.get("position_limit"))
        stamp = now_iso()
        conn = self._connect()
        try:
            if plan_id:
                if not conn.execute("SELECT 1 FROM subscription_plans WHERE id=?", (plan_id,)).fetchone():
                    raise SubscriptionError("Пакет не найден.")
                conn.execute(
                    """UPDATE subscription_plans SET code=?,name=?,description=?,price_amount=?,
                           currency=?,term_days=?,daily_operation_limit=?,position_limit=?,
                           is_public=?,is_active=?,display_order=?,updated_at=? WHERE id=?""",
                    (
                        code, name, str(payload.get("description") or "").strip(), price,
                        str(payload.get("currency") or "KZT").upper(), term_days, daily_limit,
                        position_limit, int(bool(payload.get("is_public", True))),
                        int(bool(payload.get("is_active", True))), int(payload.get("display_order") or 100),
                        stamp, plan_id,
                    ),
                )
            else:
                cursor = conn.execute(
                    """INSERT INTO subscription_plans(
                           code,name,description,price_amount,currency,term_days,
                           daily_operation_limit,position_limit,is_public,is_active,
                           display_order,created_by,created_at,updated_at
                       ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    (
                        code, name, str(payload.get("description") or "").strip(), price,
                        str(payload.get("currency") or "KZT").upper(), term_days, daily_limit,
                        position_limit, int(bool(payload.get("is_public", True))),
                        int(bool(payload.get("is_active", True))), int(payload.get("display_order") or 100),
                        int(actor_user_id), stamp, stamp,
                    ),
                )
                plan_id = int(cursor.lastrowid)
            features = payload.get("features")
            if isinstance(features, dict):
                for feature_code, raw in features.items():
                    feature_code = str(feature_code).strip()
                    if not feature_code:
                        continue
                    enabled = bool(raw.get("is_enabled", True)) if isinstance(raw, dict) else bool(raw)
                    limit_value = _optional_limit(raw.get("limit_value")) if isinstance(raw, dict) else None
                    config = raw.get("config", {}) if isinstance(raw, dict) else {}
                    conn.execute(
                        """INSERT INTO subscription_features(
                               code,name,description,category,is_active,created_at,updated_at
                           ) VALUES(?,?,'','custom',1,?,?) ON CONFLICT(code) DO NOTHING""",
                        (feature_code, feature_code, stamp, stamp),
                    )
                    conn.execute(
                        """INSERT INTO subscription_plan_features(
                               plan_id,feature_code,is_enabled,limit_value,config_json
                           ) VALUES(?,?,?,?,?) ON CONFLICT(plan_id,feature_code) DO UPDATE SET
                               is_enabled=excluded.is_enabled,limit_value=excluded.limit_value,
                               config_json=excluded.config_json""",
                        (plan_id, feature_code, int(enabled), limit_value, json.dumps(config, ensure_ascii=False)),
                    )
            marketplaces = payload.get("marketplaces")
            if isinstance(marketplaces, dict):
                for marketplace, raw in marketplaces.items():
                    if marketplace not in MARKETPLACE_CODES or not isinstance(raw, dict):
                        continue
                    conn.execute(
                        """INSERT INTO subscription_plan_marketplace_limits(
                               plan_id,marketplace_code,is_enabled,position_limit,daily_operation_limit
                           ) VALUES(?,?,?,?,?) ON CONFLICT(plan_id,marketplace_code) DO UPDATE SET
                               is_enabled=excluded.is_enabled,position_limit=excluded.position_limit,
                               daily_operation_limit=excluded.daily_operation_limit""",
                        (
                            plan_id, marketplace, int(bool(raw.get("is_enabled", True))),
                            _optional_limit(raw.get("position_limit")),
                            _optional_limit(raw.get("daily_operation_limit"), maximum=100000),
                        ),
                    )
            conn.commit()
            return self._plan_row(conn, plan_id)
        except integrity_error_types() as exc:
            conn.rollback()
            raise SubscriptionError("Код пакета уже используется.") from exc
        finally:
            conn.close()

    def save_addon(self, payload: dict[str, Any], actor_user_id: int) -> dict[str, Any]:
        addon_id = int(payload.get("id") or 0)
        code = str(payload.get("code") or "").strip().casefold()
        name = str(payload.get("name") or "").strip()
        positions = int(payload.get("extra_positions") or 0)
        price = float(payload.get("price_amount") or 0)
        if not re.fullmatch(r"[a-z][a-z0-9_-]{1,39}", code) or len(name) < 2:
            raise SubscriptionError("Проверьте код и название дополнения.")
        if positions <= 0 or positions > 10_000_000 or price < 0:
            raise SubscriptionError("Количество позиций должно быть положительным, цена — неотрицательной.")
        term_days = _optional_limit(payload.get("term_days"), maximum=3650)
        stamp = now_iso()
        conn = self._connect()
        try:
            values = (
                code, name, str(payload.get("description") or "").strip(), positions, price,
                str(payload.get("currency") or "KZT").upper(), term_days,
                int(bool(payload.get("is_public", True))), int(bool(payload.get("is_active", True))),
                int(payload.get("display_order") or 100), stamp,
            )
            if addon_id:
                conn.execute(
                    """UPDATE subscription_addons SET code=?,name=?,description=?,extra_positions=?,
                           price_amount=?,currency=?,term_days=?,is_public=?,is_active=?,
                           display_order=?,updated_at=? WHERE id=?""",
                    values + (addon_id,),
                )
            else:
                cursor = conn.execute(
                    """INSERT INTO subscription_addons(
                           code,name,description,extra_positions,price_amount,currency,term_days,
                           is_public,is_active,display_order,created_by,created_at,updated_at
                       ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                    values[:-1] + (int(actor_user_id), stamp, stamp),
                )
                addon_id = int(cursor.lastrowid)
            conn.commit()
            row = conn.execute("SELECT * FROM subscription_addons WHERE id=?", (addon_id,)).fetchone()
            if not row:
                raise SubscriptionError("Дополнение не найдено.")
            return dict(row)
        except integrity_error_types() as exc:
            conn.rollback()
            raise SubscriptionError("Код дополнения уже используется.") from exc
        finally:
            conn.close()

    def _active_subscription(
        self,
        conn: sqlite3.Connection,
        tenant_id: int,
    ) -> dict[str, Any] | None:
        now = datetime.now().astimezone()

        rows = [
            dict(row)
            for row in conn.execute(
                """SELECT s.*,
                          p.code plan_code,
                          p.name plan_name,
                          p.description plan_description,
                          p.daily_operation_limit,
                          p.position_limit
                   FROM tenant_subscriptions s
                   JOIN subscription_plans p
                     ON p.id=s.plan_id
                   WHERE s.tenant_id=?
                     AND s.status IN (
                         'active',
                         'scheduled'
                     )
                   ORDER BY
                     COALESCE(
                         s.starts_at,
                         s.reviewed_at,
                         s.requested_at
                     ) DESC,
                     s.id DESC""",
                (int(tenant_id),),
            ).fetchall()
        ]

        selected = None

        for value in rows:
            starts = _parse_time(
                value.get("starts_at")
            )
            ends = _parse_time(
                value.get("ends_at")
            )

            if starts and starts > now:
                continue

            if ends and ends <= now:
                continue

            selected = value
            break

        if selected is None:
            return None

        if selected.get("status") == "scheduled":
            stamp = now_iso()

            conn.execute(
                """UPDATE tenant_subscriptions
                   SET status='expired',
                       updated_at=?
                   WHERE tenant_id=?
                     AND status='active'
                     AND id<>?""",
                (
                    stamp,
                    int(tenant_id),
                    int(selected["id"]),
                ),
            )

            conn.execute(
                """UPDATE tenant_subscriptions
                   SET status='active',
                       updated_at=?
                   WHERE id=?""",
                (
                    stamp,
                    int(selected["id"]),
                ),
            )

            conn.execute(
                """UPDATE tenants
                   SET plan_code=?,
                       updated_at=?
                   WHERE id=?""",
                (
                    str(selected["plan_code"]),
                    stamp,
                    int(tenant_id),
                ),
            )

            conn.commit()
            selected["status"] = "active"

        return selected

    def entitlement(self, tenant_id: int) -> dict[str, Any]:
        conn = self._connect()
        try:
            subscription = self._active_subscription(conn, tenant_id)
            if not subscription:
                return {
                    "status": "missing", "active": False,
                    "message": "Нет активного подтверждённого пакета.",
                    "subscription": None, "features": {}, "marketplaces": {},
                }
            plan_id = int(subscription["plan_id"])
            features = {
                str(row["feature_code"]): bool(row["is_enabled"])
                for row in conn.execute(
                    "SELECT feature_code,is_enabled FROM subscription_plan_features WHERE plan_id=?",
                    (plan_id,),
                ).fetchall()
            }
            today = datetime.now().astimezone().date().isoformat()
            total_daily_used = int(conn.execute(
                """SELECT COALESCE(SUM(used_count),0) FROM tenant_daily_usage
                   WHERE tenant_id=? AND usage_date=? AND metric_code='operations'""",
                (int(tenant_id), today),
            ).fetchone()[0])
            current_counts = {
                str(row["marketplace_code"]): int(row["count_value"] or 0)
                for row in conn.execute(
                    """SELECT marketplace_code,COUNT(*) count_value
                       FROM tenant_catalog_products WHERE tenant_id=? AND active=1
                       GROUP BY marketplace_code""",
                    (int(tenant_id),),
                ).fetchall()
            }
            addon_positions: dict[str, int] = {}
            now = datetime.now().astimezone()
            for row in conn.execute(
                """SELECT marketplace_code,extra_positions,quantity,starts_at,ends_at
                   FROM tenant_subscription_addons
                   WHERE tenant_id=? AND status='active'""",
                (int(tenant_id),),
            ).fetchall():
                starts, ends = _parse_time(row["starts_at"]), _parse_time(row["ends_at"])
                if (starts and starts > now) or (ends and ends < now):
                    continue
                key = str(row["marketplace_code"] or "")
                addon_positions[key] = addon_positions.get(key, 0) + int(row["extra_positions"] or 0) * int(row["quantity"] or 1)
            configured = {
                str(row["marketplace_code"]): dict(row)
                for row in conn.execute(
                    """SELECT marketplace_code,is_enabled,position_limit,daily_operation_limit
                       FROM subscription_plan_marketplace_limits WHERE plan_id=?""",
                    (plan_id,),
                ).fetchall()
            }
            marketplaces: dict[str, dict[str, Any]] = {}
            for code in sorted(MARKETPLACE_CODES):
                row = configured.get(code, {})
                enabled = bool(row.get("is_enabled", features.get(f"marketplace.{code}", True)))
                base_position = row.get("position_limit") if "position_limit" in row else subscription.get("position_limit")
                base_daily = row.get("daily_operation_limit") if "daily_operation_limit" in row else subscription.get("daily_operation_limit")
                extra = addon_positions.get("") or 0
                extra += addon_positions.get(code) or 0
                limit = None if base_position is None else int(base_position) + extra
                used = current_counts.get(code, 0)
                daily_used = int(conn.execute(
                    """SELECT COALESCE(SUM(used_count),0) FROM tenant_daily_usage
                       WHERE tenant_id=? AND usage_date=? AND marketplace_code=?
                         AND metric_code='operations'""",
                    (int(tenant_id), today, code),
                ).fetchone()[0])
                marketplaces[code] = {
                    "enabled": enabled,
                    "position_limit": limit,
                    "base_position_limit": base_position,
                    "extra_positions": extra,
                    "positions_used": used,
                    "positions_remaining": None if limit is None else max(0, limit - used),
                    "daily_operation_limit": base_daily,
                    "daily_operations_used": daily_used,
                    "daily_operations_remaining": None if base_daily is None else max(0, int(base_daily) - daily_used),
                }
            subscription["active"] = True
            return {
                "status": "active", "active": True, "message": "",
                "subscription": subscription, "features": features,
                "daily_operation_limit": subscription.get("daily_operation_limit"),
                "daily_operations_used": total_daily_used,
                "daily_operations_remaining": None if subscription.get("daily_operation_limit") is None else max(
                    0, int(subscription["daily_operation_limit"]) - total_daily_used
                ),
                "marketplaces": marketplaces,
            }
        finally:
            conn.close()

    def operation_error(self, tenant_id: int, marketplace_code: str) -> str | None:
        value = self.entitlement(tenant_id)
        if not value["active"]:
            return "Нет активного пакета. Выберите пакет и дождитесь подтверждения супер-администратора."
        if not value["features"].get("operations", False):
            return "Запуск операций не входит в пакет компании."
        marketplace = value["marketplaces"].get(marketplace_code)
        if marketplace_code in MARKETPLACE_CODES and (not marketplace or not marketplace["enabled"]):
            return "Эта площадка не входит в пакет компании."
        overall_remaining = value.get("daily_operations_remaining")
        if overall_remaining is not None and overall_remaining <= 0:
            return "Дневной лимит запусков исчерпан. Увеличьте пакет или обратитесь к супер-администратору."
        if marketplace and marketplace.get("daily_operations_remaining") is not None and marketplace["daily_operations_remaining"] <= 0:
            return f"Дневной лимит запусков для {marketplace_code} исчерпан."
        return None

    def consume_operation(self, tenant_id: int, marketplace_code: str) -> None:
        entitlement = self.entitlement(tenant_id)
        error = self.operation_error(tenant_id, marketplace_code)
        if error:
            raise SubscriptionLimitError(error)
        stamp = now_iso()
        today = datetime.now().astimezone().date().isoformat()
        conn = self._connect()
        try:
            # Serialize usage changes per company. The pre-check above keeps the
            # common error path cheap; these checks inside the lock are the
            # authoritative guard against simultaneous workers overshooting a
            # daily limit.
            if isinstance(conn, PostgresConnection):
                conn.execute("SELECT id FROM tenants WHERE id=? FOR UPDATE", (int(tenant_id),))
            else:
                conn.execute("BEGIN IMMEDIATE")
            total_used = int(conn.execute(
                """SELECT COALESCE(SUM(used_count),0) FROM tenant_daily_usage
                   WHERE tenant_id=? AND usage_date=? AND metric_code='operations'""",
                (int(tenant_id), today),
            ).fetchone()[0])
            marketplace_used = int(conn.execute(
                """SELECT COALESCE(SUM(used_count),0) FROM tenant_daily_usage
                   WHERE tenant_id=? AND usage_date=? AND marketplace_code=?
                     AND metric_code='operations'""",
                (int(tenant_id), today, str(marketplace_code or "")),
            ).fetchone()[0])
            overall_limit = entitlement.get("daily_operation_limit")
            marketplace = entitlement.get("marketplaces", {}).get(marketplace_code, {})
            marketplace_limit = marketplace.get("daily_operation_limit")
            if overall_limit is not None and total_used >= int(overall_limit):
                raise SubscriptionLimitError(
                    "Дневной лимит запусков исчерпан. Увеличьте пакет или обратитесь к супер-администратору."
                )
            if marketplace_limit is not None and marketplace_used >= int(marketplace_limit):
                raise SubscriptionLimitError(
                    f"Дневной лимит запусков для {marketplace_code} исчерпан."
                )
            conn.execute(
                """INSERT INTO tenant_daily_usage(
                       tenant_id,usage_date,marketplace_code,metric_code,used_count,updated_at
                   ) VALUES(?,?,?,'operations',1,?)
                   ON CONFLICT(tenant_id,usage_date,marketplace_code,metric_code)
                   DO UPDATE SET used_count=tenant_daily_usage.used_count+1,
                                 updated_at=excluded.updated_at""",
                (int(tenant_id), today, str(marketplace_code or ""), stamp),
            )
            conn.commit()
        except Exception:
            conn.rollback()
            raise
        finally:
            conn.close()

    def release_operation(self, tenant_id: int, marketplace_code: str) -> None:
        today = datetime.now().astimezone().date().isoformat()
        conn = self._connect()
        try:
            conn.execute(
                """UPDATE tenant_daily_usage SET used_count=MAX(0,used_count-1),updated_at=?
                   WHERE tenant_id=? AND usage_date=? AND marketplace_code=?
                     AND metric_code='operations'""",
                (now_iso(), int(tenant_id), today, str(marketplace_code or "")),
            )
            conn.commit()
        finally:
            conn.close()

    def assert_position_capacity(self, tenant_id: int, marketplace_code: str, requested: int) -> None:
        value = self.entitlement(tenant_id)
        if not value["active"]:
            raise SubscriptionLimitError(
                "Каталог не сохранён: нет активного подтверждённого пакета."
            )
        marketplace = value["marketplaces"].get(marketplace_code, {})
        if not marketplace.get("enabled", False):
            raise SubscriptionLimitError("Площадка не включена в пакет компании.")
        limit = marketplace.get("position_limit")
        if limit is not None and int(requested) > int(limit):
            missing = int(requested) - int(limit)
            raise SubscriptionLimitError(
                f"Недостаточно позиций для {marketplace_code}: доступно {limit}, "
                f"получено {requested}. Увеличьте лимит минимум на {missing} позиций."
            )

    def request_plan(self, tenant_id: int, plan_code: str, requested_by: int | None) -> dict[str, Any]:
        conn = self._connect()
        try:
            plan = conn.execute(
                """SELECT * FROM subscription_plans
                   WHERE code=? AND is_active=1 AND is_public=1""",
                (str(plan_code).strip().casefold(),),
            ).fetchone()
            if not plan:
                raise SubscriptionError("Выбранный пакет недоступен.")
            if str(plan["code"]) == "trial" and conn.execute(
                """SELECT 1 FROM tenant_subscriptions s
                   JOIN subscription_plans p ON p.id=s.plan_id
                   WHERE s.tenant_id=? AND p.code='trial'""",
                (int(tenant_id),),
            ).fetchone():
                raise SubscriptionError("Бесплатный пробный период уже использован этой компанией.")
            self._active_subscription(
                conn,
                int(tenant_id),
            )

            if conn.execute(
                """SELECT 1
                   FROM tenant_subscriptions
                   WHERE tenant_id=?
                     AND status IN (
                         'pending',
                         'awaiting_invoice',
                         'awaiting_payment',
                         'payment_review',
                         'payment_rejected',
                         'scheduled'
                     )""",
                (int(tenant_id),),
            ).fetchone():
                raise SubscriptionError(
                    "У компании уже есть незавершённая заявка на пакет."
                )
            stamp = now_iso()
            snapshot = json.dumps(self._plan_row(conn, int(plan["id"])), ensure_ascii=False, default=str)
            cursor = conn.execute(
                """INSERT INTO tenant_subscriptions(
                       tenant_id,plan_id,status,requested_by,requested_at,price_amount,currency,
                       term_days,plan_snapshot_json,created_at,updated_at
                   ) VALUES(?,?,'pending',?,?,?,?,?,?,?,?)""",
                (
                    int(tenant_id), int(plan["id"]), requested_by, stamp,
                    float(plan["price_amount"]), str(plan["currency"]), int(plan["term_days"]),
                    snapshot, stamp, stamp,
                ),
            )
            conn.commit()
            return dict(conn.execute(
                "SELECT * FROM tenant_subscriptions WHERE id=?", (int(cursor.lastrowid),)
            ).fetchone())
        finally:
            conn.close()

    def review_subscription(
        self,
        subscription_id: int,
        decision: str,
        actor_user_id: int,
        *,
        term_days: int | None = None,
        price_amount: float | None = None,
        starts_at: str | None = None,
        ends_at: str | None = None,
        review_note: str = "",
    ) -> dict[str, Any]:
        decision = str(
            decision
        ).strip().casefold()

        if decision not in {
            "approved",
            "rejected",
        }:
            raise SubscriptionError(
                "Решение должно быть approved "
                "или rejected."
            )

        conn = self._connect()

        try:
            row = conn.execute(
                """SELECT *
                   FROM tenant_subscriptions
                   WHERE id=?""",
                (int(subscription_id),),
            ).fetchone()

            if not row:
                raise SubscriptionError(
                    "Заявка на пакет не найдена."
                )

            if str(row["status"]) != "pending":
                raise SubscriptionError(
                    "Заявка уже обработана."
                )

            stamp = now_iso()

            if decision == "approved":
                now = datetime.now().astimezone()

                tenant = conn.execute(
                    """SELECT status
                       FROM tenants
                       WHERE id=?""",
                    (int(row["tenant_id"]),),
                ).fetchone()

                if (
                    not tenant
                    or str(tenant["status"])
                    not in {
                        "approved",
                        "active",
                    }
                ):
                    raise SubscriptionError(
                        "Сначала "
                        "необходимо "
                        "подтвердить "
                        "компанию."
                    )

                days = int(
                    term_days
                    or row["term_days"]
                )

                if not 1 <= days <= 3650:
                    raise SubscriptionError(
                        "Срок должен быть "
                        "от 1 до 3650 дней."
                    )

                price = float(
                    row["price_amount"]
                    if price_amount is None
                    else price_amount
                )

                if price < 0:
                    raise SubscriptionError(
                        "Цена не может быть "
                        "отрицательной."
                    )

                plan_code = str(
                    conn.execute(
                        """SELECT code
                           FROM subscription_plans
                           WHERE id=?""",
                        (int(row["plan_id"]),),
                    ).fetchone()[0]
                )

                current = self._active_subscription(
                    conn,
                    int(row["tenant_id"]),
                )

                # Legacy is only a compatibility entitlement for companies
                # created before commercial subscription assignment.
                # The first real package must replace it immediately.
                if (
                    current
                    and str(
                        current.get("plan_code")
                        or ""
                    ).casefold()
                    == "legacy"
                ):
                    current = None

                start_value = (
                    starts_at
                    if starts_at not in (None, "")
                    else row["starts_at"]
                )

                explicit_start = (
                    _parse_time(start_value)
                    if start_value
                    else None
                )

                if start_value and explicit_start is None:
                    raise SubscriptionError(
                        "Некорректная дата "
                        "начала пакета."
                    )

                if explicit_start:
                    start_dt = explicit_start
                else:
                    current_end = (
                        _parse_time(
                            current.get("ends_at")
                        )
                        if current
                        else None
                    )

                    start_dt = (
                        current_end
                        if (
                            current_end
                            and current_end > now
                        )
                        else now
                    )

                end_value = (
                    ends_at
                    if ends_at not in (None, "")
                    else row["ends_at"]
                )

                explicit_end = (
                    _parse_time(end_value)
                    if end_value
                    else None
                )

                if end_value and explicit_end is None:
                    raise SubscriptionError(
                        "Некорректная дата "
                        "окончания пакета."
                    )

                if plan_code != "trial":
                    if (
                        explicit_start
                        and explicit_end
                        and explicit_end <= explicit_start
                    ):
                        raise SubscriptionError(
                            "Дата "
                            "окончания "
                            "должна "
                            "быть "
                            "позже "
                            "даты "
                            "начала."
                        )

                    approved_start = (
                        explicit_start.isoformat(
                            timespec="seconds"
                        )
                        if explicit_start
                        else None
                    )

                    approved_end = (
                        explicit_end.isoformat(
                            timespec="seconds"
                        )
                        if explicit_end
                        else None
                    )

                    conn.execute(
                        """UPDATE tenant_subscriptions
                           SET status='awaiting_invoice',
                               reviewed_by=?,
                               reviewed_at=?,
                               starts_at=?,
                               ends_at=?,
                               term_days=?,
                               price_amount=?,
                               review_note=?,
                               updated_at=?
                           WHERE id=?""",
                        (
                            int(actor_user_id),
                            stamp,
                            approved_start,
                            approved_end,
                            days,
                            price,
                            review_note,
                            stamp,
                            int(subscription_id),
                        ),
                    )

                    conn.commit()

                    return dict(
                        conn.execute(
                            """SELECT *
                               FROM tenant_subscriptions
                               WHERE id=?""",
                            (int(subscription_id),),
                        ).fetchone()
                    )

                end_dt = (
                    explicit_end
                    or (
                        start_dt
                        + timedelta(days=days)
                    )
                )

                if end_dt <= start_dt:
                    raise SubscriptionError(
                        "Дата окончания должна "
                        "быть позже даты начала."
                    )

                if explicit_end:
                    seconds = (
                        end_dt - start_dt
                    ).total_seconds()

                    days = max(
                        1,
                        int(
                            (
                                seconds
                                + 86399
                            )
                            // 86400
                        ),
                    )

                starts = start_dt.isoformat(
                    timespec="seconds"
                )

                ends = end_dt.isoformat(
                    timespec="seconds"
                )

                new_status = (
                    "scheduled"
                    if start_dt > now
                    else "active"
                )

                if new_status == "active":
                    conn.execute(
                        """UPDATE tenant_subscriptions
                           SET status='cancelled',
                               updated_at=?
                           WHERE tenant_id=?
                             AND status IN (
                                 'active',
                                 'scheduled'
                             )
                             AND id<>?""",
                        (
                            stamp,
                            int(row["tenant_id"]),
                            int(subscription_id),
                        ),
                    )
                else:
                    conn.execute(
                        """UPDATE tenant_subscriptions
                           SET status='cancelled',
                               updated_at=?
                           WHERE tenant_id=?
                             AND status='scheduled'
                             AND id<>?""",
                        (
                            stamp,
                            int(row["tenant_id"]),
                            int(subscription_id),
                        ),
                    )

                conn.execute(
                    """UPDATE tenant_subscriptions
                       SET status=?,
                           reviewed_by=?,
                           reviewed_at=?,
                           starts_at=?,
                           ends_at=?,
                           term_days=?,
                           price_amount=?,
                           review_note=?,
                           updated_at=?
                       WHERE id=?""",
                    (
                        new_status,
                        int(actor_user_id),
                        stamp,
                        starts,
                        ends,
                        days,
                        price,
                        review_note,
                        stamp,
                        int(subscription_id),
                    ),
                )

                if new_status == "active":
                    conn.execute(
                        """UPDATE tenants
                           SET plan_code=?,
                               updated_at=?
                           WHERE id=?""",
                        (
                            plan_code,
                            stamp,
                            int(row["tenant_id"]),
                        ),
                    )

            else:
                conn.execute(
                    """UPDATE tenant_subscriptions
                       SET status='rejected',
                           reviewed_by=?,
                           reviewed_at=?,
                           review_note=?,
                           updated_at=?
                       WHERE id=?""",
                    (
                        int(actor_user_id),
                        stamp,
                        review_note,
                        stamp,
                        int(subscription_id),
                    ),
                )

            conn.commit()

            return dict(
                conn.execute(
                    """SELECT *
                       FROM tenant_subscriptions
                       WHERE id=?""",
                    (int(subscription_id),),
                ).fetchone()
            )

        finally:
            conn.close()

    def assign_plan(
        self,
        tenant_id: int,
        plan_code: str,
        actor_user_id: int,
        *,
        starts_at: str | None = None,
        ends_at: str | None = None,
        price_amount: float | None = None,
        review_note: str = "",
    ) -> dict[str, Any]:
        code = str(
            plan_code or ""
        ).strip().casefold()

        conn = self._connect()

        try:
            plan = conn.execute(
                """SELECT *
                   FROM subscription_plans
                   WHERE code=?
                     AND is_active=1""",
                (code,),
            ).fetchone()

            if not plan or code == "legacy":
                raise SubscriptionError(
                    "Пакет недоступен "
                    "для назначения."
                )

            stamp = now_iso()

            conn.execute(
                """UPDATE tenant_subscriptions
                   SET status='cancelled',
                       updated_at=?
                   WHERE tenant_id=?
                     AND status='pending'""",
                (
                    stamp,
                    int(tenant_id),
                ),
            )

            snapshot = json.dumps(
                self._plan_row(
                    conn,
                    int(plan["id"]),
                ),
                ensure_ascii=False,
                default=str,
            )

            cursor = conn.execute(
                """INSERT INTO tenant_subscriptions(
                       tenant_id,
                       plan_id,
                       status,
                       requested_by,
                       requested_at,
                       price_amount,
                       currency,
                       term_days,
                       plan_snapshot_json,
                       review_note,
                       created_at,
                       updated_at
                   )
                   VALUES(
                       ?,?,
                       'pending',
                       ?,?,?,?,?,?,?,?,?
                   )""",
                (
                    int(tenant_id),
                    int(plan["id"]),
                    int(actor_user_id),
                    stamp,
                    float(
                        plan["price_amount"]
                        if price_amount is None
                        else price_amount
                    ),
                    str(plan["currency"]),
                    int(plan["term_days"]),
                    snapshot,
                    str(review_note or ""),
                    stamp,
                    stamp,
                ),
            )

            request_id = int(
                cursor.lastrowid
            )

            conn.commit()

        finally:
            conn.close()

        return self.review_subscription(
            request_id,
            "approved",
            int(actor_user_id),
            starts_at=starts_at,
            ends_at=ends_at,
            price_amount=price_amount,
            review_note=review_note,
        )

    def request_addon(
        self, tenant_id: int, addon_code: str, marketplace_code: str,
        quantity: int, requested_by: int,
    ) -> dict[str, Any]:
        if marketplace_code not in MARKETPLACE_CODES:
            raise SubscriptionError("Выберите площадку для дополнительных позиций.")
        quantity = int(quantity or 1)
        if not 1 <= quantity <= 100:
            raise SubscriptionError("Количество дополнений должно быть от 1 до 100.")
        conn = self._connect()
        try:
            subscription = self._active_subscription(conn, tenant_id)
            if not subscription:
                raise SubscriptionError("Сначала требуется активный пакет.")
            addon = conn.execute(
                "SELECT * FROM subscription_addons WHERE code=? AND is_active=1 AND is_public=1",
                (str(addon_code).strip().casefold(),),
            ).fetchone()
            if not addon:
                raise SubscriptionError("Дополнение недоступно.")
            stamp = now_iso()
            cursor = conn.execute(
                """INSERT INTO tenant_subscription_addons(
                       tenant_id,subscription_id,addon_id,marketplace_code,status,quantity,
                       requested_by,requested_at,price_amount,currency,extra_positions,
                       created_at,updated_at
                   ) VALUES(?,?,?,?,'pending',?,?,?,?,?,?,?,?)""",
                (
                    int(tenant_id), int(subscription["id"]), int(addon["id"]), marketplace_code,
                    quantity, int(requested_by), stamp, float(addon["price_amount"]) * quantity,
                    str(addon["currency"]), int(addon["extra_positions"]), stamp, stamp,
                ),
            )
            conn.commit()
            return dict(conn.execute(
                "SELECT * FROM tenant_subscription_addons WHERE id=?", (int(cursor.lastrowid),)
            ).fetchone())
        finally:
            conn.close()

    def review_addon(self, request_id: int, decision: str, actor_user_id: int, review_note: str = "") -> dict[str, Any]:
        decision = str(decision).strip().casefold()
        if decision not in {"approved", "rejected"}:
            raise SubscriptionError("Решение должно быть approved или rejected.")
        conn = self._connect()
        try:
            row = conn.execute(
                "SELECT * FROM tenant_subscription_addons WHERE id=?", (int(request_id),)
            ).fetchone()
            if not row or str(row["status"]) != "pending":
                raise SubscriptionError("Заявка не найдена или уже обработана.")
            stamp = now_iso()
            status = "active" if decision == "approved" else "rejected"
            starts = stamp if status == "active" else None
            ends = None
            if status == "active":
                subscription = conn.execute(
                    "SELECT ends_at FROM tenant_subscriptions WHERE id=?", (row["subscription_id"],)
                ).fetchone()
                ends = subscription["ends_at"] if subscription else None
            conn.execute(
                """UPDATE tenant_subscription_addons SET status=?,reviewed_by=?,reviewed_at=?,
                       starts_at=?,ends_at=?,review_note=?,updated_at=? WHERE id=?""",
                (status, int(actor_user_id), stamp, starts, ends, review_note, stamp, int(request_id)),
            )
            conn.commit()
            return dict(conn.execute(
                "SELECT * FROM tenant_subscription_addons WHERE id=?", (int(request_id),)
            ).fetchone())
        finally:
            conn.close()

    def tenant_snapshot(self, tenant_id: int) -> dict[str, Any]:
        conn = self._connect()
        try:
            requests = [dict(row) for row in conn.execute(
                """SELECT s.*,p.code plan_code,p.name plan_name
                   FROM tenant_subscriptions s JOIN subscription_plans p ON p.id=s.plan_id
                   WHERE s.tenant_id=? ORDER BY s.id DESC LIMIT 20""",
                (int(tenant_id),),
            ).fetchall()]
            addon_requests = [dict(row) for row in conn.execute(
                """SELECT a.*,o.code addon_code,o.name addon_name
                   FROM tenant_subscription_addons a JOIN subscription_addons o ON o.id=a.addon_id
                   WHERE a.tenant_id=? ORDER BY a.id DESC LIMIT 20""",
                (int(tenant_id),),
            ).fetchall()]
        finally:
            conn.close()
        return {
            "entitlement": self.entitlement(tenant_id),
            "plans": self.plans(public_only=True),
            "addons": self.addons(public_only=True),
            "requests": requests,
            "addon_requests": addon_requests,
        }

    def admin_snapshot(self) -> dict[str, Any]:
        conn = self._connect()
        try:
            pending = [dict(row) for row in conn.execute(
                """SELECT s.*,p.code plan_code,p.name plan_name,t.name tenant_name
                   FROM tenant_subscriptions s
                   JOIN subscription_plans p ON p.id=s.plan_id
                   JOIN tenants t ON t.id=s.tenant_id
                   WHERE s.status='pending' ORDER BY s.requested_at"""
            ).fetchall()]
            pending_addons = [dict(row) for row in conn.execute(
                """SELECT a.*,o.code addon_code,o.name addon_name,t.name tenant_name
                   FROM tenant_subscription_addons a
                   JOIN subscription_addons o ON o.id=a.addon_id
                   JOIN tenants t ON t.id=a.tenant_id
                   WHERE a.status='pending' ORDER BY a.requested_at"""
            ).fetchall()]
            payments = [dict(row) for row in conn.execute(
                """SELECT pay.*,t.name tenant_name,p.name plan_name,p.code plan_code
                   FROM subscription_payments pay
                   JOIN tenants t ON t.id=pay.tenant_id
                   JOIN tenant_subscriptions s ON s.id=pay.subscription_id
                   JOIN subscription_plans p ON p.id=s.plan_id
                   ORDER BY pay.paid_at DESC LIMIT 500"""
            ).fetchall()]
            active = [dict(row) for row in conn.execute(
                """SELECT s.*,t.name tenant_name,p.name plan_name,p.code plan_code
                   FROM tenant_subscriptions s JOIN tenants t ON t.id=s.tenant_id
                   JOIN subscription_plans p ON p.id=s.plan_id
                   WHERE s.status='active' ORDER BY s.ends_at"""
            ).fetchall()]
        finally:
            conn.close()
        return {
            "plans": self.plans(), "addons": self.addons(),
            "pending_subscriptions": pending, "pending_addons": pending_addons,
            "payments": payments, "active_subscriptions": active,
        }

    def active_subscriptions(self) -> list[dict[str, Any]]:
        """Small company-list projection without loading package editors/payments."""
        conn = self._connect()
        try:
            return [dict(row) for row in conn.execute(
                """SELECT s.id,s.tenant_id,s.status,s.price_amount,s.currency,
                          s.term_days,s.starts_at,s.ends_at,s.reviewed_at,
                          t.name tenant_name,p.name plan_name,p.code plan_code
                   FROM tenant_subscriptions s JOIN tenants t ON t.id=s.tenant_id
                   JOIN subscription_plans p ON p.id=s.plan_id
                   WHERE s.status='active' ORDER BY s.ends_at"""
            ).fetchall()]
        finally:
            conn.close()
