BEGIN;

ALTER TABLE app.app_users
    ADD COLUMN IF NOT EXISTS email_verified_at text;

ALTER TABLE app.app_users
    ADD COLUMN IF NOT EXISTS session_version integer
        NOT NULL DEFAULT 0;


WITH first_install AS (
    INSERT INTO app.metadata(key, value)
    VALUES(
        'schema_email_auth_notifications_v1',
        CURRENT_TIMESTAMP::text
    )
    ON CONFLICT(key) DO NOTHING
    RETURNING key
)
UPDATE app.app_users
SET email_verified_at =
    COALESCE(email_verified_at, created_at)
WHERE email_verified_at IS NULL
  AND EXISTS(
      SELECT 1 FROM first_install
  );


CREATE TABLE IF NOT EXISTS app.auth_tokens (
    id bigint GENERATED BY DEFAULT
        AS IDENTITY PRIMARY KEY,

    user_id bigint NOT NULL
        REFERENCES app.app_users(id)
        ON DELETE CASCADE,

    purpose text NOT NULL,

    token_hash text NOT NULL UNIQUE,

    expires_at text NOT NULL,

    consumed_at text,

    created_at text NOT NULL,

    request_ip text NOT NULL DEFAULT '',

    metadata_json text NOT NULL DEFAULT '{}',

    CHECK(
        purpose IN (
            'verify_email',
            'password_reset',
            'user_invitation',
            'email_change'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_active
ON app.auth_tokens(
    user_id,
    purpose,
    consumed_at,
    expires_at,
    id DESC
);


CREATE TABLE IF NOT EXISTS app.email_outbox (
    id bigint GENERATED BY DEFAULT
        AS IDENTITY PRIMARY KEY,

    tenant_id bigint
        REFERENCES app.tenants(id)
        ON DELETE CASCADE,

    user_id bigint
        REFERENCES app.app_users(id)
        ON DELETE SET NULL,

    recipient text NOT NULL,

    template_key text NOT NULL,

    subject text NOT NULL,

    payload_json text NOT NULL,

    status text NOT NULL DEFAULT 'pending'
        CHECK(
            status IN (
                'pending',
                'sending',
                'retry',
                'sent',
                'failed'
            )
        ),

    attempt_count integer
        NOT NULL DEFAULT 0
        CHECK(attempt_count >= 0),

    next_attempt_at text NOT NULL,

    last_error text NOT NULL DEFAULT '',

    dedupe_key text NOT NULL UNIQUE,

    created_at text NOT NULL,

    updated_at text NOT NULL,

    sent_at text
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_due
ON app.email_outbox(
    status,
    next_attempt_at,
    id
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_user
ON app.email_outbox(
    user_id,
    id DESC
);


CREATE TABLE IF NOT EXISTS app.notification_preferences (
    user_id bigint NOT NULL
        REFERENCES app.app_users(id)
        ON DELETE CASCADE,

    category text NOT NULL,

    in_app_enabled smallint
        NOT NULL DEFAULT 1
        CHECK(in_app_enabled IN (0,1)),

    email_enabled smallint
        NOT NULL DEFAULT 1
        CHECK(email_enabled IN (0,1)),

    telegram_enabled smallint
        NOT NULL DEFAULT 1
        CHECK(telegram_enabled IN (0,1)),

    created_at text NOT NULL,

    updated_at text NOT NULL,

    PRIMARY KEY(
        user_id,
        category
    ),

    CHECK(
        category IN (
            'security',
            'billing',
            'marketplaces',
            'operations'
        )
    )
);

CREATE INDEX IF NOT EXISTS
idx_notification_preferences_user
ON app.notification_preferences(
    user_id,
    category
);

COMMIT;
