-- SPYON-AUTO-MIGRATION
BEGIN;

CREATE TABLE IF NOT EXISTS app.tenant_addon_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    addon_id bigint NOT NULL REFERENCES app.subscription_addons(id),
    addon_code text NOT NULL,
    marketplace_code text NOT NULL,
    positions integer NOT NULL,
    quantity integer NOT NULL,
    unit_price double precision NOT NULL,
    total_price double precision NOT NULL,
    currency text NOT NULL DEFAULT 'KZT',
    valid_until text NOT NULL,
    status text NOT NULL DEFAULT 'awaiting_payment'
        CHECK(status IN ('awaiting_payment','under_review','payment_rejected','active','cancelled','superseded')),
    created_by bigint REFERENCES app.app_users(id),
    superseded_by bigint,
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_addon_orders_tenant
ON app.tenant_addon_orders(tenant_id,status,marketplace_code,created_at DESC);

CREATE TABLE IF NOT EXISTS app.tenant_addon_invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL UNIQUE REFERENCES app.tenant_addon_orders(id),
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    invoice_number text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'issued'
        CHECK(status IN ('issued','paid','cancelled','superseded')),
    unit_price double precision NOT NULL,
    total_price double precision NOT NULL,
    currency text NOT NULL DEFAULT 'KZT',
    seller_snapshot_json text NOT NULL DEFAULT '{}',
    buyer_snapshot_json text NOT NULL DEFAULT '{}',
    line_items_json text NOT NULL DEFAULT '[]',
    issued_at text NOT NULL,
    due_at text NOT NULL,
    pdf_path text NOT NULL DEFAULT '',
    pdf_sha256 text NOT NULL DEFAULT '',
    created_by bigint REFERENCES app.app_users(id),
    cancelled_by bigint REFERENCES app.app_users(id),
    cancelled_at text,
    cancel_reason text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_addon_invoices_tenant
ON app.tenant_addon_invoices(tenant_id,status,issued_at DESC);

CREATE TABLE IF NOT EXISTS app.tenant_addon_payment_proofs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES app.tenant_addon_orders(id),
    invoice_id bigint NOT NULL REFERENCES app.tenant_addon_invoices(id),
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    status text NOT NULL DEFAULT 'under_review'
        CHECK(status IN ('under_review','approved','rejected')),
    original_filename text NOT NULL DEFAULT '',
    stored_path text NOT NULL UNIQUE,
    mime_type text NOT NULL DEFAULT '',
    file_size bigint NOT NULL DEFAULT 0,
    sha256 text NOT NULL DEFAULT '',
    uploaded_by bigint REFERENCES app.app_users(id),
    uploaded_at text NOT NULL,
    reviewed_by bigint REFERENCES app.app_users(id),
    reviewed_at text,
    review_note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_addon_payment_proofs_review
ON app.tenant_addon_payment_proofs(status,uploaded_at DESC,tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_addon_payment_proofs_order
ON app.tenant_addon_payment_proofs(order_id,id DESC);

INSERT INTO app.metadata(key,value)
VALUES('schema_addon_billing_v1',CURRENT_TIMESTAMP::text)
ON CONFLICT(key) DO NOTHING;

COMMIT;
