-- Spyon Telegram authentication and notification delivery v1 (PostgreSQL).
-- Additive and data-preserving: no existing rows are changed or removed.
-- Apply only after a verified backup and staging rehearsal.

BEGIN;

CREATE TABLE IF NOT EXISTS app.telegram_user_links (
    user_id bigint PRIMARY KEY REFERENCES app.app_users(id) ON DELETE CASCADE,
    tenant_id bigint REFERENCES app.tenants(id) ON DELETE CASCADE,
    chat_id bigint NOT NULL UNIQUE,
    telegram_user_id bigint NOT NULL UNIQUE,
    telegram_username text NOT NULL DEFAULT '',
    telegram_display_name text NOT NULL DEFAULT '',
    is_enabled smallint NOT NULL DEFAULT 1 CHECK(is_enabled IN (0,1)),
    notification_start_id bigint NOT NULL DEFAULT 0,
    linked_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_telegram_user_links_tenant
    ON app.telegram_user_links(tenant_id,is_enabled);

CREATE TABLE IF NOT EXISTS app.telegram_notification_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint NOT NULL
        REFERENCES app.app_notifications(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES app.app_users(id) ON DELETE CASCADE,
    tenant_id bigint REFERENCES app.tenants(id) ON DELETE CASCADE,
    chat_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'pending'
        CHECK(status IN ('pending','retry','sent','failed')),
    attempt_count integer NOT NULL DEFAULT 0 CHECK(attempt_count >= 0),
    next_attempt_at text NOT NULL,
    telegram_message_id bigint,
    last_error text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL,
    sent_at text,
    UNIQUE(notification_id,chat_id)
);
CREATE INDEX IF NOT EXISTS idx_telegram_deliveries_pending
    ON app.telegram_notification_deliveries(status,next_attempt_at,id);
CREATE INDEX IF NOT EXISTS idx_telegram_deliveries_user
    ON app.telegram_notification_deliveries(user_id,id DESC);

INSERT INTO app.metadata(key,value)
VALUES('schema_telegram_notifications_v1', CURRENT_TIMESTAMP::text)
ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value;

COMMIT;
