-- Spyon tenant inventory and cross-marketplace matching v1 (PostgreSQL).
-- Additive and data-preserving: no DROP, DELETE, TRUNCATE, or automatic merge.
-- Apply only after backup and a successful staging rehearsal.

BEGIN;

CREATE TABLE IF NOT EXISTS app.tenant_inventory_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    internal_sku text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    quantity_on_hand bigint NOT NULL DEFAULT 0 CHECK(quantity_on_hand >= 0),
    purchase_price_kzt double precision CHECK(purchase_price_kzt IS NULL OR purchase_price_kzt >= 0),
    target_markup_percent double precision NOT NULL DEFAULT 20
        CHECK(target_markup_percent >= 0 AND target_markup_percent <= 1000),
    notes text NOT NULL DEFAULT '',
    created_by bigint REFERENCES app.app_users(id) ON DELETE SET NULL,
    updated_by bigint REFERENCES app.app_users(id) ON DELETE SET NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(tenant_id,id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_inventory_internal_sku
    ON app.tenant_inventory_products(tenant_id,internal_sku)
    WHERE internal_sku<>'';
CREATE INDEX IF NOT EXISTS idx_tenant_inventory_updated
    ON app.tenant_inventory_products(tenant_id,updated_at DESC);

CREATE TABLE IF NOT EXISTS app.tenant_product_listings (
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    listing_code text NOT NULL,
    inventory_product_id bigint NOT NULL,
    marketplace_code text NOT NULL,
    tenant_seller_id bigint,
    source_product_code text NOT NULL,
    match_method text NOT NULL DEFAULT 'MANUAL',
    match_score double precision,
    confirmed_by bigint REFERENCES app.app_users(id) ON DELETE SET NULL,
    confirmed_at text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    PRIMARY KEY(tenant_id,listing_code),
    CONSTRAINT fk_tenant_product_listing_inventory
        FOREIGN KEY(tenant_id,inventory_product_id)
        REFERENCES app.tenant_inventory_products(tenant_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tenant_product_listings_inventory
    ON app.tenant_product_listings(tenant_id,inventory_product_id,marketplace_code);
CREATE INDEX IF NOT EXISTS idx_tenant_product_listings_source
    ON app.tenant_product_listings(
        tenant_id,marketplace_code,tenant_seller_id,source_product_code
    );

CREATE TABLE IF NOT EXISTS app.tenant_product_match_decisions (
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    source_listing_code text NOT NULL,
    candidate_listing_code text NOT NULL,
    decision text NOT NULL CHECK(decision IN ('confirmed','rejected')),
    match_method text NOT NULL DEFAULT '',
    match_score double precision,
    reason text NOT NULL DEFAULT '',
    updated_by bigint REFERENCES app.app_users(id) ON DELETE SET NULL,
    updated_at text NOT NULL,
    PRIMARY KEY(tenant_id,source_listing_code,candidate_listing_code)
);
CREATE INDEX IF NOT EXISTS idx_tenant_match_decisions_candidate
    ON app.tenant_product_match_decisions(
        tenant_id,candidate_listing_code,decision
    );

CREATE TABLE IF NOT EXISTS app.tenant_inventory_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL,
    inventory_product_id bigint NOT NULL,
    event_type text NOT NULL,
    details_json text NOT NULL DEFAULT '{}',
    created_by bigint REFERENCES app.app_users(id) ON DELETE SET NULL,
    created_at text NOT NULL,
    CONSTRAINT fk_tenant_inventory_event_item
        FOREIGN KEY(tenant_id,inventory_product_id)
        REFERENCES app.tenant_inventory_products(tenant_id,id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tenant_inventory_events_item
    ON app.tenant_inventory_events(
        tenant_id,inventory_product_id,created_at DESC
    );

-- PostgreSQL startup is read-only and does not execute SQLite role seeding.
-- Add only the new system-role defaults; existing per-user overrides remain intact.
WITH permission_defaults(role_code,permission_code) AS (
    VALUES
        ('admin','view_inventory'),
        ('admin','manage_inventory'),
        ('admin','manage_product_matching'),
        ('operator','view_inventory'),
        ('operator','manage_inventory')
)
INSERT INTO app.tenant_role_permissions(
    tenant_id,role_code,permission_code,is_enabled,created_at,updated_at
)
SELECT
    tenants.id,permission_defaults.role_code,permission_defaults.permission_code,
    1,CURRENT_TIMESTAMP::text,CURRENT_TIMESTAMP::text
FROM app.tenants AS tenants
CROSS JOIN permission_defaults
WHERE true
ON CONFLICT(tenant_id,role_code,permission_code) DO NOTHING;

INSERT INTO app.metadata(key,value)
VALUES('schema_inventory_matching_v1', CURRENT_TIMESTAMP::text)
ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value;

COMMIT;
