-- ITP Market multi-seller v1 (PostgreSQL / app schema)
-- Additive and data-preserving: no DROP, DELETE, or key rewrites.
-- Apply only after a verified backup and an explicit maintenance decision.

BEGIN;

ALTER TABLE app.tenant_marketplace_sellers
    ADD COLUMN IF NOT EXISTS config_json text NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS discovery_status text NOT NULL DEFAULT 'idle',
    ADD COLUMN IF NOT EXISTS approval_status text NOT NULL DEFAULT 'draft',
    ADD COLUMN IF NOT EXISTS discovery_json text NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS submitted_by bigint,
    ADD COLUMN IF NOT EXISTS submitted_at text,
    ADD COLUMN IF NOT EXISTS reviewed_by bigint,
    ADD COLUMN IF NOT EXISTS reviewed_at text,
    ADD COLUMN IF NOT EXISTS review_note text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS product_count bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_sync_at text,
    ADD COLUMN IF NOT EXISTS last_status text,
    ADD COLUMN IF NOT EXISTS last_error text NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_tenant_sellers_approval
    ON app.tenant_marketplace_sellers(
        tenant_id, marketplace_code, approval_status, status
    );

CREATE TABLE IF NOT EXISTS app.tenant_seller_catalog_products (
    tenant_id bigint NOT NULL,
    marketplace_code text NOT NULL,
    tenant_seller_id bigint NOT NULL,
    source_product_code text NOT NULL,
    catalog_id bigint,
    seller_sku text NOT NULL DEFAULT '',
    title text NOT NULL DEFAULT '',
    brand text NOT NULL DEFAULT '',
    model text NOT NULL DEFAULT '',
    source_url text NOT NULL DEFAULT '',
    image_url text NOT NULL DEFAULT '',
    category_name text NOT NULL DEFAULT '',
    price_amount double precision,
    currency text NOT NULL DEFAULT '',
    availability_status text NOT NULL DEFAULT '',
    attributes_json text NOT NULL DEFAULT '[]',
    metadata_json text NOT NULL DEFAULT '{}',
    active bigint NOT NULL DEFAULT 1,
    first_seen_at text NOT NULL,
    last_seen_at text NOT NULL,
    source_updated_at text,
    PRIMARY KEY(
        tenant_id, marketplace_code, tenant_seller_id, source_product_code
    ),
    CONSTRAINT fk_seller_products_tenant
        FOREIGN KEY(tenant_id) REFERENCES app.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_seller_products_seller
        FOREIGN KEY(tenant_seller_id)
        REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE,
    CONSTRAINT fk_seller_products_catalog
        FOREIGN KEY(catalog_id) REFERENCES app.tenant_catalogs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tenant_seller_products_visible
    ON app.tenant_seller_catalog_products(
        tenant_id, marketplace_code, tenant_seller_id, active, last_seen_at
    );

CREATE TABLE IF NOT EXISTS app.tenant_seller_price_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    marketplace_code text NOT NULL,
    tenant_seller_id bigint NOT NULL
        REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE,
    source_product_code text NOT NULL,
    seller_sku text NOT NULL DEFAULT '',
    price_amount double precision,
    price_before_discount double precision,
    discount_percent double precision,
    currency text NOT NULL DEFAULT '',
    status text NOT NULL,
    error text NOT NULL DEFAULT '',
    captured_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_seller_price_history
    ON app.tenant_seller_price_snapshots(
        tenant_id, marketplace_code, tenant_seller_id,
        source_product_code, captured_at DESC
    );

CREATE TABLE IF NOT EXISTS app.tenant_seller_offer_scans (
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    marketplace_code text NOT NULL,
    tenant_seller_id bigint NOT NULL
        REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE,
    source_product_code text NOT NULL,
    status text NOT NULL,
    offers_count bigint NOT NULL DEFAULT 0,
    competitor_count bigint NOT NULL DEFAULT 0,
    min_price double precision,
    max_price double precision,
    duration_seconds double precision,
    error text NOT NULL DEFAULT '',
    checked_at text NOT NULL,
    PRIMARY KEY(
        tenant_id, marketplace_code, tenant_seller_id, source_product_code
    )
);

CREATE TABLE IF NOT EXISTS app.tenant_seller_offer_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id) ON DELETE CASCADE,
    marketplace_code text NOT NULL,
    tenant_seller_id bigint NOT NULL
        REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE,
    source_product_code text NOT NULL,
    merchant_id text NOT NULL DEFAULT '',
    merchant_name text NOT NULL DEFAULT '',
    merchant_sku text NOT NULL DEFAULT '',
    price_amount double precision,
    currency text NOT NULL DEFAULT '',
    merchant_rating double precision,
    merchant_reviews bigint,
    is_own bigint NOT NULL DEFAULT 0,
    captured_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tenant_seller_offer_history
    ON app.tenant_seller_offer_snapshots(
        tenant_id, marketplace_code, tenant_seller_id,
        source_product_code, captured_at DESC
    );

CREATE TABLE IF NOT EXISTS app.seller_encrypted_credentials (
    credential_ref text PRIMARY KEY,
    tenant_id bigint NOT NULL,
    tenant_seller_id bigint NOT NULL,
    marketplace_code text NOT NULL,
    credential_name text NOT NULL,
    ciphertext text NOT NULL,
    key_id text NOT NULL,
    created_by bigint,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    UNIQUE(tenant_id, tenant_seller_id, marketplace_code, credential_name),
    CONSTRAINT fk_seller_credentials_tenant
        FOREIGN KEY(tenant_id) REFERENCES app.tenants(id) ON DELETE CASCADE,
    CONSTRAINT fk_seller_credentials_seller
        FOREIGN KEY(tenant_seller_id)
        REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE,
    CONSTRAINT fk_seller_credentials_creator
        FOREIGN KEY(created_by) REFERENCES app.app_users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_seller_encrypted_credentials_tenant
    ON app.seller_encrypted_credentials(
        tenant_id, tenant_seller_id, marketplace_code, credential_name
    );

ALTER TABLE app.operation_schedules
    ADD COLUMN IF NOT EXISTS tenant_seller_id bigint;
ALTER TABLE app.schedule_runs
    ADD COLUMN IF NOT EXISTS tenant_seller_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname='fk_operation_schedules_seller'
          AND conrelid='app.operation_schedules'::regclass
    ) THEN
        ALTER TABLE app.operation_schedules
            ADD CONSTRAINT fk_operation_schedules_seller
            FOREIGN KEY(tenant_seller_id)
            REFERENCES app.tenant_marketplace_sellers(id) ON DELETE CASCADE
            NOT VALID;
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname='fk_schedule_runs_seller'
          AND conrelid='app.schedule_runs'::regclass
    ) THEN
        ALTER TABLE app.schedule_runs
            ADD CONSTRAINT fk_schedule_runs_seller
            FOREIGN KEY(tenant_seller_id)
            REFERENCES app.tenant_marketplace_sellers(id) ON DELETE SET NULL
            NOT VALID;
    END IF;
END $$;

INSERT INTO app.tenant_marketplace_sellers(
    tenant_id, marketplace_code, external_seller_id, display_name, source_url,
    status, config_json, discovery_status, approval_status, discovery_json,
    submitted_by, submitted_at, reviewed_by, reviewed_at, review_note,
    product_count, last_sync_at, last_status, last_error, created_at, updated_at
)
SELECT
    ti.tenant_id, ti.integration_code, ti.seller_identifier,
    ti.seller_name, ti.seller_url,
    CASE WHEN ti.status='active' AND ti.approval_status='approved'
         THEN 'active' ELSE ti.status END,
    ti.config_json, ti.discovery_status, ti.approval_status, ti.discovery_json,
    ti.submitted_by, ti.submitted_at, ti.reviewed_by, ti.reviewed_at,
    ti.review_note, ti.product_count, ti.last_sync_at, ti.last_status,
    COALESCE(ti.last_error,''), ti.created_at, ti.updated_at
FROM app.tenant_integrations ti
WHERE BTRIM(COALESCE(ti.seller_identifier,''))<>''
  AND ti.seller_identifier NOT LIKE 'candidate:%'
ON CONFLICT(tenant_id, marketplace_code, external_seller_id) DO NOTHING;

UPDATE app.tenant_marketplace_sellers s
SET approval_status = CASE
        WHEN s.status='active' THEN 'approved'
        WHEN s.status='pending' THEN 'pending'
        WHEN s.status='rejected' THEN 'rejected'
        ELSE s.approval_status END;

INSERT INTO app.tenant_seller_catalog_products(
    tenant_id, marketplace_code, tenant_seller_id, source_product_code,
    catalog_id, seller_sku, title, brand, model, source_url, image_url,
    category_name, price_amount, currency, availability_status,
    attributes_json, metadata_json, active, first_seen_at, last_seen_at,
    source_updated_at
)
SELECT
    tcp.tenant_id, tcp.marketplace_code,
    COALESCE(tcp.tenant_seller_id, chosen.id), tcp.source_product_code,
    tcp.catalog_id, tcp.seller_sku, tcp.title, tcp.brand, tcp.model,
    tcp.source_url, tcp.image_url, tcp.category_name, tcp.price_amount,
    tcp.currency, tcp.availability_status, tcp.attributes_json,
    tcp.metadata_json, tcp.active, tcp.first_seen_at, tcp.last_seen_at,
    tcp.source_updated_at
FROM app.tenant_catalog_products tcp
LEFT JOIN app.tenant_integrations ti
  ON ti.tenant_id=tcp.tenant_id
 AND ti.integration_code=tcp.marketplace_code
LEFT JOIN LATERAL (
    SELECT s.id
    FROM app.tenant_marketplace_sellers s
    WHERE s.tenant_id=tcp.tenant_id
      AND s.marketplace_code=tcp.marketplace_code
      AND (
          s.external_seller_id=ti.seller_identifier
          OR 1=(
              SELECT COUNT(*)
              FROM app.tenant_marketplace_sellers one_seller
              WHERE one_seller.tenant_id=tcp.tenant_id
                AND one_seller.marketplace_code=tcp.marketplace_code
          )
      )
    ORDER BY CASE WHEN s.external_seller_id=ti.seller_identifier THEN 0 ELSE 1 END,
             s.id
    LIMIT 1
) chosen ON TRUE
WHERE COALESCE(tcp.tenant_seller_id, chosen.id) IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO app.metadata(key,value)
VALUES('schema_multi_seller_v1_backfilled', CURRENT_TIMESTAMP::text)
ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value;

COMMIT;
