-- SPYON-AUTO-MIGRATION
BEGIN;

-- Registration fields are additive so a production database created before
-- self-service onboarding can accept the same payload as a fresh install.
ALTER TABLE app.tenants
    ADD COLUMN IF NOT EXISTS workspace_profile_json text
        NOT NULL DEFAULT '{}';

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS capabilities_json text
        NOT NULL DEFAULT '[]';

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS consent_version text
        NOT NULL DEFAULT '';

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS consent_at text;

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS locale text
        NOT NULL DEFAULT 'ru';

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS source_page text
        NOT NULL DEFAULT 'public_site';

ALTER TABLE app.registration_requests
    ADD COLUMN IF NOT EXISTS workspace_profile_json text
        NOT NULL DEFAULT '{}';

ALTER TABLE app.app_users
    ADD COLUMN IF NOT EXISTS platform_role text
        NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS app.subscription_features (
    code text PRIMARY KEY,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    category text NOT NULL DEFAULT 'general',
    is_active smallint NOT NULL DEFAULT 1,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.subscription_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    price_amount double precision NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'KZT',
    term_days integer NOT NULL DEFAULT 30,
    daily_operation_limit integer,
    position_limit integer,
    is_public smallint NOT NULL DEFAULT 1,
    is_active smallint NOT NULL DEFAULT 1,
    display_order integer NOT NULL DEFAULT 100,
    created_by bigint REFERENCES app.app_users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.subscription_plan_features (
    plan_id bigint NOT NULL REFERENCES app.subscription_plans(id),
    feature_code text NOT NULL REFERENCES app.subscription_features(code),
    is_enabled smallint NOT NULL DEFAULT 1,
    limit_value integer,
    config_json text NOT NULL DEFAULT '{}',
    PRIMARY KEY(plan_id, feature_code)
);

CREATE TABLE IF NOT EXISTS app.subscription_plan_marketplace_limits (
    plan_id bigint NOT NULL REFERENCES app.subscription_plans(id),
    marketplace_code text NOT NULL,
    is_enabled smallint NOT NULL DEFAULT 1,
    position_limit integer,
    daily_operation_limit integer,
    PRIMARY KEY(plan_id, marketplace_code)
);

CREATE TABLE IF NOT EXISTS app.subscription_addons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    description text NOT NULL DEFAULT '',
    extra_positions integer NOT NULL,
    price_amount double precision NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'KZT',
    term_days integer,
    is_public smallint NOT NULL DEFAULT 1,
    is_active smallint NOT NULL DEFAULT 1,
    display_order integer NOT NULL DEFAULT 100,
    created_by bigint REFERENCES app.app_users(id),
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS app.tenant_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    plan_id bigint NOT NULL REFERENCES app.subscription_plans(id),
    status text NOT NULL DEFAULT 'pending',
    requested_by bigint REFERENCES app.app_users(id),
    requested_at text NOT NULL,
    reviewed_by bigint REFERENCES app.app_users(id),
    reviewed_at text,
    starts_at text,
    ends_at text,
    price_amount double precision NOT NULL,
    currency text NOT NULL,
    term_days integer NOT NULL,
    plan_snapshot_json text NOT NULL DEFAULT '{}',
    review_note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tenant_subscriptions_current
ON app.tenant_subscriptions(tenant_id, status, starts_at, ends_at);

CREATE TABLE IF NOT EXISTS app.subscription_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    subscription_id bigint NOT NULL UNIQUE
        REFERENCES app.tenant_subscriptions(id),
    amount double precision NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'KZT',
    status text NOT NULL DEFAULT 'confirmed',
    paid_at text NOT NULL,
    period_start text NOT NULL,
    period_end text NOT NULL,
    term_days integer NOT NULL,
    months_count double precision NOT NULL DEFAULT 1,
    confirmed_by bigint REFERENCES app.app_users(id),
    note text NOT NULL DEFAULT '',
    created_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_subscription_payments_time
ON app.subscription_payments(paid_at DESC, tenant_id);

CREATE TABLE IF NOT EXISTS app.tenant_subscription_addons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    subscription_id bigint REFERENCES app.tenant_subscriptions(id),
    addon_id bigint NOT NULL REFERENCES app.subscription_addons(id),
    marketplace_code text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'pending',
    quantity integer NOT NULL DEFAULT 1,
    requested_by bigint REFERENCES app.app_users(id),
    requested_at text NOT NULL,
    reviewed_by bigint REFERENCES app.app_users(id),
    reviewed_at text,
    starts_at text,
    ends_at text,
    price_amount double precision NOT NULL,
    currency text NOT NULL,
    extra_positions integer NOT NULL,
    review_note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tenant_subscription_addons_current
ON app.tenant_subscription_addons(tenant_id, status, marketplace_code, starts_at, ends_at);

CREATE TABLE IF NOT EXISTS app.billing_sequences (
    sequence_year integer PRIMARY KEY,
    last_value bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS app.subscription_invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    subscription_id bigint NOT NULL
        REFERENCES app.tenant_subscriptions(id),
    invoice_number text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'issued',
    months_count integer NOT NULL,
    unit_price double precision NOT NULL DEFAULT 0,
    subtotal_amount double precision NOT NULL DEFAULT 0,
    vat_rate double precision NOT NULL DEFAULT 0,
    vat_amount double precision NOT NULL DEFAULT 0,
    total_amount double precision NOT NULL DEFAULT 0,
    currency text NOT NULL DEFAULT 'KZT',
    seller_snapshot_json text NOT NULL DEFAULT '{}',
    buyer_snapshot_json text NOT NULL DEFAULT '{}',
    line_items_json text NOT NULL DEFAULT '[]',
    issued_at text NOT NULL,
    due_at text,
    pdf_path text NOT NULL DEFAULT '',
    pdf_sha256 text NOT NULL DEFAULT '',
    created_by bigint REFERENCES app.app_users(id),
    cancelled_by bigint REFERENCES app.app_users(id),
    cancelled_at text,
    cancel_reason text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_subscription_invoices_tenant
ON app.subscription_invoices(tenant_id, status, issued_at DESC);

CREATE INDEX IF NOT EXISTS idx_subscription_invoices_subscription
ON app.subscription_invoices(subscription_id, issued_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_invoices_open
ON app.subscription_invoices(subscription_id)
WHERE status <> 'cancelled';

CREATE TABLE IF NOT EXISTS app.subscription_payment_proofs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES app.tenants(id),
    subscription_id bigint NOT NULL
        REFERENCES app.tenant_subscriptions(id),
    invoice_id bigint NOT NULL
        REFERENCES app.subscription_invoices(id),
    status text NOT NULL DEFAULT 'under_review',
    original_filename text NOT NULL DEFAULT '',
    stored_path text NOT NULL UNIQUE,
    mime_type text NOT NULL DEFAULT '',
    file_size bigint NOT NULL DEFAULT 0,
    sha256 text NOT NULL DEFAULT '',
    uploaded_by bigint REFERENCES app.app_users(id),
    uploaded_at text NOT NULL,
    reviewed_by bigint REFERENCES app.app_users(id),
    reviewed_at text,
    review_note text NOT NULL DEFAULT '',
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_subscription_payment_proofs_invoice
ON app.subscription_payment_proofs(invoice_id, uploaded_at DESC);

CREATE INDEX IF NOT EXISTS idx_subscription_payment_proofs_tenant
ON app.subscription_payment_proofs(tenant_id, status, uploaded_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_payment_proofs_review_open
ON app.subscription_payment_proofs(invoice_id)
WHERE status = 'under_review';

INSERT INTO app.metadata(key, value)
VALUES('schema_self_service_billing_v1', CURRENT_TIMESTAMP::text)
ON CONFLICT(key) DO NOTHING;

COMMIT;
